language: node_js

node_js:
 - 10.12.0

branches:
  only:
  - master

install:
 - npm install -g istanbul
 - npm install

before_script:

script:
  - npm run build
  - npm run test
  - npm run coverage

after_script:
  - cp ./dist/* ./docs/ -r

