apiVersion: v1
kind: Secret
metadata:
  name: mongo-express
data:
  db-server-url: "bW9uZ29kYi5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsCg==" # mongodb.default.svc.cluster.local
  db-server-port: "MjcwMTcK" # 27017
  db-admin-username: "cm9vdAo=" # root
  db-admin-password: "bXlwYXNzd29yZAo=" # mypassword
