apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  selector:
    app.kubernetes.io/name: mongo-express
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8081
