= Semaphore

:javaFile: {javaCodeDir}/DataStructures.java

Ignite's counting distributed semaphore implementation and behavior is similar to the concept of a well-known `java.util.concurrent.Semaphore`. As any other semaphore it maintains a set of permits that are taken using `acquire()` method and released with `release()` counterpart allowing to restrict access to some logical or physical resource or synchronize execution flow. The only difference is that Ignite's semaphore empowers you to fulfill these kind of actions not only in boundaries of a single JVM but rather a cluster wide, across many remote nodes.

You can create a distributed semaphore as follows:
[source, java]
----
include::{javaFile}[tags=semaphore, indent=0]
----

Once the semaphore is created, it can be used concurrently by multiple cluster nodes in order to implement some distributed logic or restrict access to a distributed resource like in the following example:

[source, java]
----
include::{javaFile}[tags=use-semaphore, indent=0]
----

