# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    cooldown:
      deafult-days: 10
    ignore:
      - dependency-name: "org.apache.calcite:calcite-core"
      - dependency-name: "org.apache.calcite:calcite-linq4j"
      - dependency-name: "org.apache.calcite.avatica:avatica-core"

      - dependency-name: "org.springframework:*"
      - dependency-name: "org.springframework.*:*"

      - dependency-name: "junit:junit"

      - dependency-name: "com.h2database:h2"