= The Ignite Sandbox

== Overview
Ignite allows using a user-defined code that can be a compute job, event filter, message listener, etc.
This user-defined code can utilize Java features to get access to host resources.
For example, it can create/update/delete files; create sockets; read/update/delete system properties; use reflection API and so on.
To restrict user-defined code options you may use the Ignite Sandbox based on the Java Sandbox model.

You can read about the Java Sandbox model link:https://docs.oracle.com/en/java/javase/11/security/java-se-platform-security-architecture.html#GUID-C203D80F-C730-45C3-AB95-D4E61FD6D89C[here].

There are a few conditions to run user-defined code with restrictions:

- link:/security/authentication[GridSecurityProcessor] is installed;
- the method _GridSecurityProcessor#sandboxEnabled_ returns true;
- link:https://docs.oracle.com/javase/8/docs/technotes/guides/security/spec/security-spec.doc6.html#a19349[SecurityManager] is installed.


If the Ignite Sandbox is turned on, you can see the following trace line:
[source,text]
----
[INFO] Security status [authentication=on, sandbox=on, tls/ssl=off]
----

A user-defined code is always executed on behalf of the security subject that initiates its execution.
The security subject's sandbox link:https://docs.oracle.com/en/java/javase/11/security/java-se-platform-security-architecture.html#GUID-DEA8EAB1-CF00-4658-AA6D-D2C9754C8B37[permissions] define actions that a user-defined code can perform.
The Ignite Sandbox gets these permissions using the _SecuritySubject#sandboxPermissions_ method.

If a security subject doesn't have enough permissions to perform a security-sensitive operation,
an AcccessControlException appears.

NOTE: A user-defined code, when running inside the Ignite Sandbox, may use the public API of Ignite without granting any additional permissions.
