// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= SSL/TLS

:javaFile: {javaCodeDir}/Security.java
:xmlFile: code-snippets/xml/ssl.xml

This page explains how to configure SSL/TLS encryption between cluster nodes (both server and client nodes) and thin clients that connect to your cluster.

== Considerations

To ensure a sufficient level of security, we recommend that each node (server or client) has its own unique certificate in the node's keystore (including the private key).
This certificate must be trusted by all other server nodes.
//This configuration allows for an easier certificate replacement procedure (for example when they are expired).


== SSL/TLS for Nodes

To enable SSL/TLS for cluster nodes, configure an `SSLContext` factory in the node configuration.
You can use the `org.apache.ignite.ssl.SslContextFactory`, which is the default factory that uses a configurable keystore to initialize the SSL context.
//You can also implement your own `SSLContext` factory.

[CAUTION]
====
Ensure that your version of the JVM addresses
link:https://bugs.openjdk.java.net/browse/JDK-8219658[the following issue, window=_blank] that can cause deadlocks
in SSL connections. If your JVM is affected but can't be updated, then set
the link:clustering/network-configuration[`TcpDiscoverySpi.soLinger`] parameter to a non-negative value.
====

Below is an example of `SslContextFactory` configuration:

[tabs]
--
tab:XML[]
[source,xml]
----
include::{xmlFile}[tags=ignite-config;!discovery,indent=0]
----
tab:Java[]
[source,java]
----
include::{javaFile}[tag=ssl-context-factory,indent=0]
----
tab:C#/.NET[]
[source,csharp]
----

----
tab:C++[unsupported]
--

The keystore must contain the node's certificate, including its private key.
The trust store must contain the trusted certificates for all other cluster nodes.

You can define other properties, such as key algorithm, key store type, or trust manager. See the description of the properties in the <<SslContextFactory Properties>> section.

After starting the node, you should see the following messages in the logs:


[source, text,subs="verbatim,quotes"]
----
Security status [authentication=off, *tls/ssl=on*]
----



////
== SSL/TLS for Thin Clients

To enable SSL/TLS for thin clients, refer to the link:thin-clients/getting-started-with-thin-clients#enabling-ssltls-for-thin-clients[thin client documentation].
////

== SSL/TLS for Thin Clients and JDBC/ODBC [[ssl-for-clients]]

Ignite uses the same SSL/TLS properties for all clients, including thin clients and JDBC/ODBC connections. The properties are configured within the client connector configuration.
The client connector configuration is defined via the `IgniteConfiguration.clientConnectorConfiguration` property.

To enable SSL/TLS for client connections, set the `sslEnabled` property to `true` and provide an `SslContextFactory` in the client connector configuration.
You can re-use the <<SSL/TLS for Nodes,SSLContextFactory configured for nodes>>, or you can configure an SSLContext factory that will be used for client connections only.

Then, configure SSL on the client side in the same way. Refer to the specific client documentation for details.

Here is an example configuration that sets `SslContextFactory` for client connection:

[tabs]
--
tab:XML[]
[source,xml]
----
include::code-snippets/xml/thin-client-cluster-config.xml[tag=ssl-configuration,indent=0]
----
tab:Java[]
[source,java]
----
include::{javaCodeDir}/JavaThinClient.java[tag=cluster-ssl-configuration,indent=0]
----
tab:C#/.NET[]
[source,csharp]
----
include::code-snippets/dotnet/ThinClient.cs[tag=ssl,indent=0]
----
tab:C++[unsupported]
--

If you want to re-use the SSLContext factory configured for nodes, you only need to set the `sslEnabled` property to `true`, and  `ClientConnectorConfiguration` will look for the SSLContext configured in `IgniteConfiguration`:

[tabs]
--
tab:XML[]
[source,xml]
----
<property name="clientConnectorConfiguration">
    <bean class="org.apache.ignite.configuration.ClientConnectorConfiguration">
        <property name="sslEnabled" value="true"/>
    </bean>
</property>
----
tab:Java[]
[source,java]
----
include::{javaCodeDir}/JavaThinClient.java[tag=use-global-ssl,indent=0]
----
tab:C#/.NET[unsupported]
tab:C++[unsupported]
--

== Disabling Certificate Validation

In some cases, it is useful to disable certificate validation, for example when connecting to a server with a self-signed certificate.
This can be achieved by using a disabled trust manager, which can be obtained by calling the `SslContextFactory.getDisabledTrustManager()` method.

[tabs]
--
tab:XML[]
[source,xml]
----
include::code-snippets/xml/ssl-without-validation.xml[tags=ignite-config;!discovery,indent=0]
----
tab:Java[]
[source,java]
----
include::{javaFile}[tag=disable-validation,indent=0]
----
--

== Upgrading Certificates
If your SSL certificates are about to expire or have been compromised, you can install new certificates without shutting down the whole cluster.

The following is a procedure for updating certificate.

. First of all, make sure the new certificates are trusted by all cluster nodes.
This step may not be necessary if your trusted stores contain the root certificate and the new certificates are signed by the same CA.
+
--
Import the new certificate to the trusted store of every node, server or client, then run `control.sh --ssl reload`.
Also import it to the trusted stores of applications that connect to the cluster with SSL, including `control.sh` itself (`--truststore`).
`--ssl reload` does not reach applications, so restart a running Java or C++ thin client: it reads its trusted store only when it starts.

Now all nodes trust the new certificates.
--

. Import the new certificate (including the private key) to the key store of the corresponding node and remove the old certificate. Repeat this for all certificates you want to update, then run `control.sh --ssl reload`.
Check with `control.sh --ssl status` that every node serves the new certificate.

If a private key has been compromised, make sure the trusted stores no longer accept its certificate, for example by moving to a new certificate authority.
Then run `control.sh --ssl reload` and restart the nodes one at a time: a reload does not close the connections that are already open.

//Otherwise, first you have to push the trust store to all nodes one by one. It will contain trusts for both new and old certificates while you transition.

== Renewing Certificates Automatically

A node can pick up a new certificate from its key store file by itself before the current one expires.
Renewal is off by default.
To turn it on, set the `renewalEnabled` property of the SSL context factory and restart the nodes one at a time.
With renewal on, a node whose renewal settings are out of range does not start.

The node then reads the key store and trust store files again in the renewal window.
By default, the window is the last 15% of the certificate lifetime: a certificate valid for 30 days is renewed 4.5 days before it expires.
Put the new files in place before the window, and only files you are ready to use: the node picks them up by itself.
The node puts the new certificate in use only if every certificate in its chain is valid now and the chain expires later than the one in use.
If the factory serves discovery or communication, the node's own trust store must also accept the new certificate.
A changed trust store alone is not picked up.
To trust a new certificate authority, add it to the trust store of every node and run `control.sh --ssl reload` before you put certificates from it in place.

Until the files hold a newer certificate, the node keeps the one in use and reads the files again with a growing pause, from 1 minute to 1 hour by default.
While the node waits, it logs a warning once a day.
Once less than half of the window is left, or the certificate would expire before the next attempt, it logs an error instead.
If the node cannot read the files or rejects the new certificate, it logs every failed attempt and tries again.
`control.sh --ssl status` and the `NextRenewalTime` metric show when the next renewal is due.
HTTP REST takes its certificate from the Jetty configuration and is not renewed.

== SslContextFactory Properties

`SslContextFactory` supports the following properties:

[width="100%", cols="30%, 60%, 10%"]
|=================
| Property | Description | Default

|`keyAlgorithm`
|The key manager algorithm that will be used to create a key manager.
|`SunX509`

|`keyStoreFilePath`
|The path to the key store file. This is a mandatory parameter since the SSL context can not be initialized without a key manager.
|`N/A`

|`keyStorePassword`
|The key store password.
|`N/A`

|`keyStoreType`
|The key store type.
|`JKS`

|`protocol`
|The protocol for secure transport. https://docs.oracle.com/en/java/javase/11/docs/specs/security/standard-names.html#sslcontext-algorithms[Supported algorithms,window=_blank].
|`TLS`

|`renewalEnabled`
|Whether a node renews the certificate by itself before it expires.
|`false`

|`renewBeforeFraction`
|Share of the certificate lifetime, from its start to the earliest expiry in its chain, left when a node renews it. Greater than `0` and less than `1`.
|`0.15`

|`renewBefore`
|Maximum renewal window, in milliseconds, not negative. A node takes the smaller of it and the window from `renewBeforeFraction`; `0` means no maximum.
|`0`

|`renewalRetryMinInterval`
|Pause after the first renewal attempt that puts no new certificate in use, in milliseconds, greater than `0`. A node never renews more often than this.
|`60000`

|`renewalRetryMaxInterval`
|Longest pause between such attempts, in milliseconds, not less than `renewalRetryMinInterval`. If a quarter of the window is shorter, a node takes it as the longest pause, but not less than `renewalRetryMinInterval`. A node adds a random delay of up to half of every pause.
|`3600000`

|`trustStoreFilePath`
|The path to the trust store file.
|`N/A`

|`trustStorePassword`
|The trust store password.
|`N/A`

|`trustStoreType`
|The trust store type.
|`JKS`

|`trustManagers`
|A list of pre-configured trust managers.
|`N/A`
|=================
