import 'jquery';
import 'angular';
import 'angular-animate';
import 'angular-sanitize';
import 'angular-strap';
import 'angular-socket-io';
import 'angular-retina';
import 'angular-ui-router';
import 'ui-router-metatags/dist/ui-router-metatags.js';
import 'angular-smart-table';
import 'angular-ui-grid/ui-grid';
import 'angular-drag-and-drop-lists';
import 'angular-nvd3';
import 'angular-tree-control';
import 'angular-gridster';
import 'bootstrap-sass/assets/javascripts/bootstrap/carousel.js';
// import 'file-saver';
import 'jszip';
import 'query-command-supported';

import 'angular-gridster/dist/angular-gridster.min.css';
import 'angular-tree-control/css/tree-control-attribute.css';
import 'angular-tree-control/css/tree-control.css';
import 'angular-ui-grid/ui-grid.css';
import 'angular-motion/dist/angular-motion.css';