// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Executor Service

:javaFile: {javaCodeDir}/IgniteExecutorService.java

Ignite provides a distributed implementation of `java.util.concurrent.ExecutorService` that submits tasks to a cluster's server nodes for execution.
The tasks are load balanced across the cluster nodes and are guaranteed to be executed as long as there is at least one node in the cluster.

////
TODO: C# unsupported?
////
An executor service can be obtained from an instance of `Ignite`:

[source, java]
----
include::{javaFile}[tag=execute,indent=0]
----

You can also limit the set of nodes available for the executor service by specifying a link:distributed-computing/cluster-groups[cluster group]:

[source, java]
-------------------------------------------------------------------------------
include::{javaFile}[tag=cluster-group,indent=0]
-------------------------------------------------------------------------------


