/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.ignite.agent.testdrive.model;

import java.io.Serializable;

/**
 * ParkingKey definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 08/24/2015.
 */
public class ParkingKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for parkingId. */
    private int parkingId;

    /**
     * Empty constructor.
     */
    public ParkingKey() {
        // No-op.
    }

    /**
     * Full constructor.
     */
    public ParkingKey(
        int parkingId
    ) {
        this.parkingId = parkingId;
    }

    /**
     * Gets parkingId.
     *
     * @return Value for parkingId.
     */
    public int getParkingId() {
        return parkingId;
    }

    /**
     * Sets parkingId.
     *
     * @param parkingId New value for parkingId.
     */
    public void setParkingId(int parkingId) {
        this.parkingId = parkingId;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof ParkingKey))
            return false;

        ParkingKey that = (ParkingKey)o;

        if (parkingId != that.parkingId)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = parkingId;

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "ParkingKey [parkingId=" + parkingId +
            "]";
    }
}

