// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Configuring Partition Backups

include::data-modeling/data-partitioning.adoc[tag=partition-backups]

== Configuring Backups

To configure the number of backup copies, set the `backups` property in the cache configuration.

[tabs]
--
tab:XML[]
[source,xml]
----
include::code-snippets/xml/configure-backups.xml[tags=ignite-config;!discovery;!sync-mode, indent=0]
----
tab:Java[]
[source,java]
----
include::{javaCodeDir}/ConfiguringCaches.java[tag=backups,indent=0]
----
tab:C#/.NET[]
[source,csharp]
----
include::code-snippets/dotnet/DataModellingConfiguringCaches.cs[tag=backups,indent=0]
----
tab:C++[unsupported]

--

== Synchronous and Asynchronous Backups
////
TODO: explain this better
////

You can configure whether updates of primary and backup copies should be synchronous or asynchronous by specifying a write synchronization mode.
You can set the write synchronization mode in the cache configuration:


[tabs]
--
tab:XML[]
[source,xml]
----
include::code-snippets/xml/configure-backups.xml[tags=ignite-config;!discovery;!cache-mode, indent=0]
----
tab:Java[]
[source,java]
----
include::{javaCodeDir}/ConfiguringCaches.java[tag=synchronization-mode,indent=0]
----
tab:C#/.NET[]
[source,csharp]
----
include::code-snippets/dotnet/DataModellingConfiguringCaches.cs[tag=synchronization-mode,indent=0]
----
tab:C++[unsupported]
--

The write synchronization mode can be set to the following values:

[cols="1,5",opts="stretch,header"]
|===
| Value |  Description
| FULL_SYNC
| Client node will wait for write or commit to complete on all participating remote nodes (primary and backup).

|FULL_ASYNC
|Client node does not wait for responses from participating nodes, in which case remote nodes may get their state updated slightly after any of the cache write methods complete or after the Transaction.commit() method completes.

|PRIMARY_SYNC
|This is the default mode. Client node will wait for write or commit to complete on primary node, but will not wait for backups to be updated.

|===


//NOTE: Regardless of write synchronization mode, cache data will always remain fully consistent across all participating nodes when using transactions.

== Affinity Backup Filters

`RendezvousAffinityFunction` can use an affinity backup filter to control where backup copies are placed.
Backup filters are useful when cache copies must follow hardware, availability zone, rack, cell, or data center boundaries.

Ignite provides the following built-in filters:

[cols="1,3",opts="header"]
|===
| Filter | Description
| `ClusterNodeAttributeAffinityBackupFilter`
| Places backup copies on nodes that have different values of the configured node attributes.
Use it to spread partition copies across availability zones, racks, or other failure domains.

| `ClusterNodeAttributeColocatedBackupFilter`
| Places backup copies on nodes that have the same value of the configured node attribute as the primary node.
Use it to keep all copies of a partition inside the same cell or another co-location group.
For example, if nodes are grouped by a `CELL` attribute, the primary and backups for one partition are placed
on nodes from the same cell, while other partitions can be assigned to other cells.

| `MdcAffinityBackupFilter`
| Places partition copies evenly across data centers.
Use it in link:clustering/multi-data-center[multi data center deployments].
|===

[NOTE]
====
`ClusterNodeAttributeColocatedBackupFilter` intentionally co-locates partition copies in the same attribute group.
It is useful for cell-based layouts where the goal is to limit the failure impact to a cell.
It should not be used when the goal is to spread copies across data centers or availability zones.
====
