// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Apache Ignite Pub/Sub Module

Pub/Sub module is a streaming connector to inject Pub/Sub data into Ignite cache.

Starting data transfer to Ignite can be done with the following steps.

1. Import Ignite Pub/Sub Module in Maven Project
+
If you are using Maven to manage dependencies of your project, you can add Pub/Sub module dependency like this (replace '${ignite.version}' with actual Ignite version you are interested in):
+
----
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                        http://maven.apache.org/xsd/maven-4.0.0.xsd">
    ...
    <dependencies>
        ...
        <dependency>
            <groupId>org.apache.ignite</groupId>
            <artifactId>ignite-pub-sub-ext</artifactId>
            <version>${ignite-pub-sub-ext.version}</version>
        </dependency>
        ...
    </dependencies>
    ...
</project>
----
+
2. Create an Ignite configuration file (see example-ignite.xml) and make sure it is accessible from the sink.
+
3. Make sure your data input to the sink is specified. For example `input.addSink(igniteSinkObject)`