Ignite is available for Java, .NET/C#, {cpp} and other programming languages. The Java version provides the richest API.
The .NET/C#, C++, Python, etc. languages may have limited functionality. To make the Ignite documentation intuitive for all application developers,
we adhere to the following conventions:

* The information provided in this documentation applies to all programming languages unless noted otherwise.
* Code samples for different languages are provided in different tabs as shown below. For example, if you are a .NET developer, click on the .NET tab in the code examples to see .NET specific code.
+
[tabs]
--
tab:XML[]
[source,text]
----
This is a place where an example of XML configuration is provided.
Click on other tabs to view an equivalent programmatic configuration.
----
tab:Java[]
[source,text]
----
Code sample in Java. Click on other tabs to view the same example in other languages.
----
tab:C#/.NET[]
[source,text]
----
Code sample in .NET. Click on other tabs to view the same example in other languages.
----
tab:C++[]
[source,text]
----
Code sample in C++. Click on other tabs to view the same example in other languages.
----
--

* If there is no tab for a specific language, this most likely means that the functionality is not supported in that language.
