/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.ignite.internal.processors.subscription;

import java.util.ArrayList;
import java.util.Collection;
import java.util.IdentityHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CopyOnWriteArrayList;
import javax.cache.configuration.Factory;
import javax.net.ssl.SSLContext;
import org.apache.ignite.internal.GridKernalContext;
import org.apache.ignite.internal.processors.GridProcessorAdapter;
import org.apache.ignite.internal.processors.cache.persistence.DatabaseLifecycleListener;
import org.apache.ignite.internal.processors.cache.persistence.metastorage.MetastorageLifecycleListener;
import org.apache.ignite.internal.processors.cluster.IgniteChangeGlobalStateSupport;
import org.apache.ignite.internal.processors.configuration.distributed.DistributedConfigurationLifecycleListener;
import org.apache.ignite.internal.processors.metastorage.DistributedMetastorageLifecycleListener;
import org.apache.ignite.internal.processors.query.schema.SchemaChangeListener;
import org.apache.ignite.internal.ssl.SslContextProvider;
import org.apache.ignite.internal.ssl.SslContextReloadable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import static java.util.Objects.requireNonNull;

/**
 * Processor enables grid components to register listeners for events generated by other components on local node.
 *
 * It starts very first during node startup procedure so any components could use it.
 *
 * As only local events are supported, no network communication occurs during notification process.
 */
public class GridInternalSubscriptionProcessor extends GridProcessorAdapter {
    /** */
    private final List<MetastorageLifecycleListener> metastorageListeners = new ArrayList<>();

    /** */
    private final List<SchemaChangeListener> schemaChangeListeners = new ArrayList<>();

    /** */
    private final List<DistributedMetastorageLifecycleListener> distributedMetastorageListeners = new ArrayList<>();

    /** */
    private final List<DatabaseLifecycleListener> dbListeners = new ArrayList<>();

    /**
     * Listeners of distributed configuration controlled by
     * {@link org.apache.ignite.internal.processors.configuration.distributed.DistributedConfigurationProcessor}.
     */
    private final List<DistributedConfigurationLifecycleListener> distributedConfigurationListeners = new ArrayList<>();

    /** */
    private final List<IgniteChangeGlobalStateSupport> globalStateListeners = new ArrayList<>();

    /** One provider per configured factory, so transports sharing a factory share the context it hands out. */
    private final Map<Factory<SSLContext>, SslContextProvider> sslCtxProviders = new IdentityHashMap<>();

    /** Everything on this node whose certificates the reload command can replace. Read from the management pool. */
    private final Collection<SslContextReloadable> sslCtxReloadables = new CopyOnWriteArrayList<>();

    /**
     * @param ctx Kernal context.
     */
    public GridInternalSubscriptionProcessor(GridKernalContext ctx) {
        super(ctx);
    }

    /** */
    public void registerMetastorageListener(@NotNull MetastorageLifecycleListener metastorageListener) {
        requireNonNull(metastorageListener, "Metastorage subscriber should be not-null.");

        metastorageListeners.add(metastorageListener);
    }

    /** */
    public List<MetastorageLifecycleListener> getMetastorageSubscribers() {
        return metastorageListeners;
    }

    /** */
    public void registerSchemaChangeListener(@NotNull SchemaChangeListener schemaChangeListener) {
        requireNonNull(schemaChangeListener, "Schema change event subscriber should be not-null.");

        schemaChangeListeners.add(schemaChangeListener);
    }

    /** */
    public List<SchemaChangeListener> getSchemaChangeSubscribers() {
        return schemaChangeListeners;
    }

    /** */
    public void registerDistributedMetastorageListener(@NotNull DistributedMetastorageLifecycleListener lsnr) {
        requireNonNull(lsnr, "Global metastorage subscriber should be not-null.");

        distributedMetastorageListeners.add(lsnr);
    }

    /** */
    public List<DistributedMetastorageLifecycleListener> getDistributedMetastorageSubscribers() {
        return distributedMetastorageListeners;
    }

    /** */
    public void registerDatabaseListener(@NotNull DatabaseLifecycleListener databaseListener) {
        requireNonNull(databaseListener, "Database subscriber should be not-null.");

        dbListeners.add(databaseListener);
    }

    /** */
    public List<DatabaseLifecycleListener> getDatabaseListeners() {
        return dbListeners;
    }

    /** */
    public void registerDistributedConfigurationListener(
        @NotNull DistributedConfigurationLifecycleListener lifecycleListener) {
        requireNonNull(distributedConfigurationListeners, "Distributed configuration subscriber should be not-null.");

        distributedConfigurationListeners.add(lifecycleListener);
    }

    /** */
    public List<DistributedConfigurationLifecycleListener> getDistributedConfigurationListeners() {
        return distributedConfigurationListeners;
    }

    /** */
    public void registerGlobalStateListener(@NotNull IgniteChangeGlobalStateSupport globalStateListener) {
        globalStateListeners.add(globalStateListener);
    }

    /** */
    public List<IgniteChangeGlobalStateSupport> getGlobalStateListeners() {
        return globalStateListeners;
    }

    /**
     * Registers a component that has SSL configured, so that the {@code --ssl reload} command can replace its
     * certificates at runtime.
     *
     * @param reloadable Component to register.
     */
    public void registerSslContextReloadable(@NotNull SslContextReloadable reloadable) {
        requireNonNull(reloadable, "SSL context reloadable should be not-null.");

        sslCtxReloadables.add(reloadable);
    }

    /**
     * Hands out the provider that owns the context of the given factory, creating it on first ask. Transports
     * configured with the same factory get the same provider, so a reload cannot leave them on certificates read
     * at different moments.
     *
     * @param factory Factory the transport is configured with.
     * @param user Transport asking for the context, or {@code null} to say so once it has started.
     * @param interNode Whether that transport connects nodes to each other.
     * @return Provider to take the context from.
     */
    public synchronized SslContextProvider sslContextProvider(@NotNull Factory<SSLContext> factory,
        @Nullable String user, boolean interNode) {
        SslContextProvider provider = sslCtxProviders.get(factory);

        if (provider == null) {
            provider = new SslContextProvider(factory);

            sslCtxProviders.put(factory, provider);
            sslCtxReloadables.add(provider);
        }

        // A transport that can still fail to start says so later, once it has taken its port.
        if (user != null)
            provider.addUser(user, interNode);

        return provider;
    }

    /** */
    public Collection<SslContextReloadable> getSslContextReloadables() {
        return sslCtxReloadables;
    }
}
