DROP TABLE if exists Accounts;
DROP TABLE if exists Tellers;
DROP TABLE if exists Branches;
DROP TABLE if exists History;
create table if not exists Accounts (id BIGINT NOT NULL PRIMARY KEY, val BIGINT);
create table if not exists Tellers (id BIGINT NOT NULL PRIMARY KEY, val BIGINT);
create table if not exists Branches (id BIGINT NOT NULL PRIMARY KEY, val BIGINT);
create table if not exists History (id BIGINT NOT NULL PRIMARY KEY, aid BIGINT, tid BIGINT, bid BIGINT, delta BIGINT);
drop index if exists H_1;
create index H_1 on History using btree (aid, tid, bid, delta);