name: CI

on: [push, pull_request]

jobs:
  maven-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Checks
        run: |
          ./mvnw install
