package de.kp.works.ignite.transform.fleet

/*
 * Copyright (c) 2019 - 2021 Dr. Krusche & Partner PartG. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * @author Stefan Krusche, Dr. Krusche & Partner PartG
 *
 */

/**
 * The Osquery table names refer to v4.6.0
 */
object FleetTables extends Enumeration {

  type FleetTable = Value
  val ACCOUNT_POLICY_DATA: FleetTables.Value = Value(1, "account_policy_data")
  val ACPI_TABLES: FleetTables.Value = Value(2, "acpi_tables")
  val AD_CONFIG: FleetTables.Value = Value(3, "ad_config")
  val ALF: FleetTables.Value = Value(4, "alf")
  val ALF_EXCEPTIONS: FleetTables.Value = Value(5, "alf_exceptions")
  val ALF_EXPLICIT_AUTHS: FleetTables.Value = Value(6, "alf_explicit_auths")
  val APP_SCHEMES: FleetTables.Value = Value(7, "app_schemes")
  val APPARMOR_EVENTS: FleetTables.Value = Value(8, "apparmor_events")
  val APPARMOR_PROFILES: FleetTables.Value = Value(9, "apparmor_profiles")
  val APPCOMPAT_SHIMS: FleetTables.Value = Value(10, "appcompat_shims")
  val APPS: FleetTables.Value = Value(11, "apps")
  val APT_SOURCES: FleetTables.Value = Value(12, "apt_sources")
  val ARP_CACHE: FleetTables.Value = Value(13, "arp_cache")
  val ASL: FleetTables.Value = Value(14, "asl")
  val ATOM_PACKAGES: FleetTables.Value = Value(15, "atom_packages")
  val AUGEAS: FleetTables.Value = Value(16, "augeas")
  val AUTHENTICODE: FleetTables.Value = Value(17, "authenticode")
  val AUTHORIZATION_MECHANISMS: FleetTables.Value = Value(18, "authorization_mechanisms")
  val AUTHORIZATIONS: FleetTables.Value = Value(19, "authorizations")
  val AUTHORIZED_KEYS: FleetTables.Value = Value(20, "authorized_keys")
  val AUTOEXEC: FleetTables.Value = Value(21, "autoexec")
  val AZURE_INSTANCE_METADATA: FleetTables.Value = Value(22, "azure_instance_metadata")
  val AZURE_INSTANCE_TAGS: FleetTables.Value = Value(23, "azure_instance_tags")
  val BACKGROUND_ACTIVITIES_MODERATOR: FleetTables.Value = Value(24, "background_activities_moderator")
  val BATTERY: FleetTables.Value = Value(25, "battery")
  val BITLOCKER_INFO: FleetTables.Value = Value(26, "bitlocker_info")
  val BLOCK_DEVICES: FleetTables.Value = Value(27, "block_devices")
  val BPF_PROCESS_EVENTS: FleetTables.Value = Value(28, "bpf_process_events")
  val BPF_SOCKET_EVENTS: FleetTables.Value = Value(29, "bpf_socket_events")
  val BROWSER_PLUGINS: FleetTables.Value = Value(30, "browser_plugins")
  val CARBON_BLACK_INFO: FleetTables.Value = Value(31, "carbon_black_info")
  val CARVES: FleetTables.Value = Value(32, "carves")
  val CERTIFICATES: FleetTables.Value = Value(33, "certificates")
  val CHASSIS_INFO: FleetTables.Value = Value(34, "chassis_info")
  val CHOCOLATEY_PACKAGES: FleetTables.Value = Value(35, "chocolatey_packages")
  val CHROME_EXTENSION_CONTENT_SCRIPTS: FleetTables.Value = Value(36, "chrome_extension_content_scripts")
  val CHROME_EXTENSIONS: FleetTables.Value = Value(37, "chrome_extensions")
  val CONNECTIVITY: FleetTables.Value = Value(38, "connectivity")
  val CPU_INFO: FleetTables.Value = Value(39, "cpu_info")
  val CPU_TIME: FleetTables.Value = Value(40, "cpu_time")
  val CPUID: FleetTables.Value = Value(41, "cpuid")
  val CRASHES: FleetTables.Value = Value(42, "crashes")
  val CRONTAB: FleetTables.Value = Value(43, "crontab")
  val CUPS_DESTINATIONS: FleetTables.Value = Value(44, "cups_destinations")
  val CUPS_JOBS: FleetTables.Value = Value(45, "cups_jobs")
  val CURL: FleetTables.Value = Value(46, "curl")
  val CURL_CERTIFICATE: FleetTables.Value = Value(47, "curl_certificate")
  val DEB_PACKAGES: FleetTables.Value = Value(48, "deb_packages")
  val DEFAULT_ENVIRONMENT: FleetTables.Value = Value(49, "default_environment")
  val DEVICE_FILE: FleetTables.Value = Value(50, "device_file")
  val DEVICE_FIRMWARE: FleetTables.Value = Value(51, "device_firmware")
  val DEVICE_HASH: FleetTables.Value = Value(52, "device_hash")
  val DEVICE_PARTITIONS: FleetTables.Value = Value(53, "device_partitions")
  val DISK_ENCRYPTION: FleetTables.Value = Value(54, "disk_encryption")
  val DISK_EVENTS: FleetTables.Value = Value(55, "disk_events")
  val DISK_INFO: FleetTables.Value = Value(56, "disk_info")
  val DNS_CACHE: FleetTables.Value = Value(57, "dns_cache")
  val DNS_RESOLVERS: FleetTables.Value = Value(58, "dns_resolvers")
  val DOCKER_CONTAINER_FS_CHANGES: FleetTables.Value = Value(59, "docker_container_fs_changes")
  val DOCKER_CONTAINER_LABELS: FleetTables.Value = Value(60, "docker_container_labels")
  val DOCKER_CONTAINER_MOUNTS: FleetTables.Value = Value(61, "docker_container_mounts")
  val DOCKER_CONTAINER_NETWORKS: FleetTables.Value = Value(62, "docker_container_networks")
  val DOCKER_CONTAINER_PORTS: FleetTables.Value = Value(63, "docker_container_ports")
  val DOCKER_CONTAINER_PROCESSES: FleetTables.Value = Value(64, "docker_container_processes")
  val DOCKER_CONTAINER_STATS: FleetTables.Value = Value(65, "docker_container_stats")
  val DOCKER_CONTAINERS: FleetTables.Value = Value(66, "docker_containers")
  val DOCKER_IMAGE_HISTORY: FleetTables.Value = Value(67, "docker_image_history")
  val DOCKER_IMAGE_LABELS: FleetTables.Value = Value(68, "docker_image_labels")
  val DOCKER_IMAGE_LAYERS: FleetTables.Value = Value(69, "docker_image_layers")
  val DOCKER_IMAGES: FleetTables.Value = Value(70, "docker_images")
  val DOCKER_INFO: FleetTables.Value = Value(71, "docker_info")
  val DOCKER_NETWORK_LABELS: FleetTables.Value = Value(72, "docker_network_labels")
  val DOCKER_NETWORKS: FleetTables.Value = Value(73, "docker_networks")
  val DOCKER_VERSION: FleetTables.Value = Value(74, "docker_version")
  val DOCKER_VOLUME_LABELS: FleetTables.Value = Value(75, "docker_volume_labels")
  val DOCKER_VOLUMES: FleetTables.Value = Value(76, "docker_volumes")
  val DRIVERS: FleetTables.Value = Value(77, "drivers")
  val EC2_INSTANCE_METADATA: FleetTables.Value = Value(78, "ec2_instance_metadata")
  val EC2_INSTANCE_TAGS: FleetTables.Value = Value(79, "ec2_instance_tags")
  val ELF_DYNAMIC: FleetTables.Value = Value(80, "elf_dynamic")
  val ELF_INFO: FleetTables.Value = Value(81, "elf_info")
  val ELF_SECTIONS: FleetTables.Value = Value(82, "elf_sections")
  val ELF_SEGMENTS: FleetTables.Value = Value(83, "elf_segments")
  val ELF_SYMBOLS: FleetTables.Value = Value(84, "elf_symbols")
  val ETC_HOSTS: FleetTables.Value = Value(85, "etc_hosts")
  val ETC_PROTOCOLS: FleetTables.Value = Value(86, "etc_protocols")
  val ETC_SERVICES: FleetTables.Value = Value(87, "etc_services")
  val EVENT_TAPS: FleetTables.Value = Value(88, "event_taps")
  val EXAMPLE: FleetTables.Value = Value(89, "example")
  val EXTENDED_ATTRIBUTES: FleetTables.Value = Value(90, "extended_attributes")
  val FAN_SPEED_SENSORS: FleetTables.Value = Value(91, "fan_speed_sensors")
  val FBSD_KMODS: FleetTables.Value = Value(92, "fbsd_kmods")
  val FILE: FleetTables.Value = Value(93, "file")
  val FILE_EVENTS: FleetTables.Value = Value(94, "file_events")
  val FIREFOX_ADDONS: FleetTables.Value = Value(95, "firefox_addons")
  val GATEKEEPER: FleetTables.Value = Value(96, "gatekeeper")
  val GATEKEEPER_APPROVED_APPS: FleetTables.Value = Value(97, "gatekeeper_approved_apps")
  val GROUPS: FleetTables.Value = Value(98, "groups")
  val HARDWARE_EVENTS: FleetTables.Value = Value(99, "hardware_events")
  val HASH: FleetTables.Value = Value(100, "hash")
  val HOMEBREW_PACKAGES: FleetTables.Value = Value(101, "homebrew_packages")
  val HVCI_STATUS: FleetTables.Value = Value(102, "hvci_status")
  val IBRIDGE_INFO: FleetTables.Value = Value(103, "ibridge_info")
  val IE_EXTENSIONS: FleetTables.Value = Value(104, "ie_extensions")
  val INTEL_ME_INFO: FleetTables.Value = Value(105, "intel_me_info")
  val INTERFACE_ADDRESSES: FleetTables.Value = Value(106, "interface_addresses")
  val INTERFACE_DETAILS: FleetTables.Value = Value(107, "interface_details")
  val INTERFACE_IPV6: FleetTables.Value = Value(108, "interface_ipv6")
  val IOKIT_DEVICETREE: FleetTables.Value = Value(109, "iokit_devicetree")
  val IOKIT_REGISTRY: FleetTables.Value = Value(110, "iokit_registry")
  val IPTABLES: FleetTables.Value = Value(111, "iptables")
  val KERNEL_EXTENSIONS: FleetTables.Value = Value(112, "kernel_extensions")
  val KERNEL_INFO: FleetTables.Value = Value(113, "kernel_info")
  val KERNEL_MODULES: FleetTables.Value = Value(114, "kernel_modules")
  val KERNEL_PANICS: FleetTables.Value = Value(115, "kernel_panics")
  val KEYCHAIN_ACLS: FleetTables.Value = Value(116, "keychain_acls")
  val KEYCHAIN_ITEMS: FleetTables.Value = Value(117, "keychain_items")
  val KNOWN_HOSTS: FleetTables.Value = Value(118, "known_hosts")
  val KVA_SPECULATIVE_INFO: FleetTables.Value = Value(119, "kva_speculative_info")
  val LAST: FleetTables.Value = Value(120, "last")
  val LAUNCHD: FleetTables.Value = Value(121, "launchd")
  val LAUNCHD_OVERRIDES: FleetTables.Value = Value(122, "launchd_overrides")
  val LISTENING_PORTS: FleetTables.Value = Value(123, "listening_ports")
  val LLDP_NEIGHBORS: FleetTables.Value = Value(124, "lldp_neighbors")
  val LOAD_AVERAGE: FleetTables.Value = Value(125, "load_average")
  val LOCATION_SERVICES: FleetTables.Value = Value(126, "location_services")
  val LOGGED_IN_USERS: FleetTables.Value = Value(127, "logged_in_users")
  val LOGICAL_DRIVES: FleetTables.Value = Value(128, "logical_drives")
  val LOGON_SESSIONS: FleetTables.Value = Value(129, "logon_sessions")
  val LXD_CERTIFICATES: FleetTables.Value = Value(130, "lxd_certificates")
  val LXD_CLUSTER: FleetTables.Value = Value(131, "lxd_cluster")
  val LXD_CLUSTER_MEMBERS: FleetTables.Value = Value(132, "lxd_cluster_members")
  val LXD_IMAGES: FleetTables.Value = Value(133, "lxd_images")
  val LXD_INSTANCE_CONFIG: FleetTables.Value = Value(134, "lxd_instance_config")
  val LXD_INSTANCE_DEVICES: FleetTables.Value = Value(135, "lxd_instance_devices")
  val LXD_INSTANCES: FleetTables.Value = Value(136, "lxd_instances")
  val LXD_NETWORKS: FleetTables.Value = Value(137, "lxd_networks")
  val LXD_STORAGE_POOLS: FleetTables.Value = Value(138, "lxd_storage_pools")
  val MAGIC: FleetTables.Value = Value(139, "magic")
  val MANAGED_POLICIES: FleetTables.Value = Value(140, "managed_policies")
  val MD_DEVICES: FleetTables.Value = Value(141, "md_devices")
  val MD_DRIVES: FleetTables.Value = Value(142, "md_drives")
  val MD_PERSONALITIES: FleetTables.Value = Value(143, "md_personalities")
  val MDFIND: FleetTables.Value = Value(144, "mdfind")
  val MDLS: FleetTables.Value = Value(145, "mdls")
  val MEMORY_ARRAY_MAPPED_ADDRESSES: FleetTables.Value = Value(146, "memory_array_mapped_addresses")
  val MEMORY_ARRAYS: FleetTables.Value = Value(147, "memory_arrays")
  val MEMORY_DEVICE_MAPPED_ADDRESSES: FleetTables.Value = Value(148, "memory_device_mapped_addresses")
  val MEMORY_DEVICES: FleetTables.Value = Value(149, "memory_devices")
  val MEMORY_ERROR_INFO: FleetTables.Value = Value(150, "memory_error_info")
  val MEMORY_INFO: FleetTables.Value = Value(151, "memory_info")
  val MEMORY_MAP: FleetTables.Value = Value(152, "memory_map")
  val MOUNTS: FleetTables.Value = Value(153, "mounts")
  val MSR: FleetTables.Value = Value(154, "msr")
  val NFS_SHARES: FleetTables.Value = Value(155, "nfs_shares")
  val NPM_PACKAGES: FleetTables.Value = Value(156, "npm_packages")
  val NTDOMAINS: FleetTables.Value = Value(157, "ntdomains")
  val NTFS_ACL_PERMISSIONS: FleetTables.Value = Value(158, "ntfs_acl_permissions")
  val NTFS_JOURNAL_EVENTS: FleetTables.Value = Value(159, "ntfs_journal_events")
  val NVRAM: FleetTables.Value = Value(160, "nvram")
  val OEM_STRINGS: FleetTables.Value = Value(161, "oem_strings")
  val OFFICE_MRU: FleetTables.Value = Value(162, "office_mru")
  val OPERA_EXTENSIONS: FleetTables.Value = Value(163, "opera_extensions")
  val OS_VERSION: FleetTables.Value = Value(164, "os_version")
  val OSQUERY_EVENTS: FleetTables.Value = Value(165, "osquery_events")
  val OSQUERY_EXTENSIONS: FleetTables.Value = Value(166, "osquery_extensions")
  val OSQUERY_FLAGS: FleetTables.Value = Value(167, "osquery_flags")
  val OSQUERY_INFO: FleetTables.Value = Value(168, "osquery_info")
  val OSQUERY_PACKS: FleetTables.Value = Value(169, "osquery_packs")
  val OSQUERY_REGISTRY: FleetTables.Value = Value(170, "osquery_registry")
  val OSQUERY_SCHEDULE: FleetTables.Value = Value(171, "osquery_schedule")
  val PACKAGE_BOM: FleetTables.Value = Value(172, "package_bom")
  val PACKAGE_INSTALL_HISTORY: FleetTables.Value = Value(173, "package_install_history")
  val PACKAGE_RECEIPTS: FleetTables.Value = Value(174, "package_receipts")
  val PATCHES: FleetTables.Value = Value(175, "patches")
  val PCI_DEVICES: FleetTables.Value = Value(176, "pci_devices")
  val PHYSICAL_DISK_PERFORMANCE: FleetTables.Value = Value(177, "physical_disk_performance")
  val PIPES: FleetTables.Value = Value(178, "pipes")
  val PKG_PACKAGES: FleetTables.Value = Value(179, "pkg_packages")
  val PLATFORM_INFO: FleetTables.Value = Value(180, "platform_info")
  val PLIST: FleetTables.Value = Value(181, "plist")
  val PORTAGE_KEYWORDS: FleetTables.Value = Value(182, "portage_keywords")
  val PORTAGE_PACKAGES: FleetTables.Value = Value(183, "portage_packages")
  val PORTAGE_USE: FleetTables.Value = Value(184, "portage_use")
  val POWER_SENSORS: FleetTables.Value = Value(185, "power_sensors")
  val POWERSHELL_EVENTS: FleetTables.Value = Value(186, "powershell_events")
  val PREFERENCES: FleetTables.Value = Value(187, "preferences")
  val PROCESS_ENVS: FleetTables.Value = Value(188, "process_envs")
  val PROCESS_EVENTS: FleetTables.Value = Value(189, "process_events")
  val PROCESS_FILE_EVENTS: FleetTables.Value = Value(190, "process_file_events")
  val PROCESS_MEMORY_MAP: FleetTables.Value = Value(191, "process_memory_map")
  val PROCESS_NAMESPACES: FleetTables.Value = Value(192, "process_namespaces")
  val PROCESS_OPEN_FILES: FleetTables.Value = Value(193, "process_open_files")
  val PROCESS_OPEN_PIPES: FleetTables.Value = Value(194, "process_open_pipes")
  val PROCESS_OPEN_SOCKETS: FleetTables.Value = Value(195, "process_open_sockets")
  val PROCESSES: FleetTables.Value = Value(196, "processes")
  val PROGRAMS: FleetTables.Value = Value(197, "programs")
  val PROMETHEUS_METRICS: FleetTables.Value = Value(198, "prometheus_metrics")
  val PYTHON_PACKAGES: FleetTables.Value = Value(199, "python_packages")
  val QUICKLOOK_CACHE: FleetTables.Value = Value(200, "quicklook_cache")
  val REGISTRY: FleetTables.Value = Value(201, "registry")
  val ROUTES: FleetTables.Value = Value(202, "routes")
  val RPM_PACKAGE_FILES: FleetTables.Value = Value(203, "rpm_package_files")
  val RPM_PACKAGES: FleetTables.Value = Value(204, "rpm_packages")
  val RUNNING_APPS: FleetTables.Value = Value(205, "running_apps")
  val SAFARI_EXTENSIONS: FleetTables.Value = Value(206, "safari_extensions")
  val SANDBOXES: FleetTables.Value = Value(207, "sandboxes")
  val SCHEDULED_TASKS: FleetTables.Value = Value(208, "scheduled_tasks")
  val SCREENLOCK: FleetTables.Value = Value(209, "screenlock")
  val SELINUX_EVENTS: FleetTables.Value = Value(210, "selinux_events")
  val SELINUX_SETTINGS: FleetTables.Value = Value(211, "selinux_settings")
  val SERVICES: FleetTables.Value = Value(212, "services")
  val SHADOW: FleetTables.Value = Value(213, "shadow")
  val SHARED_FOLDERS: FleetTables.Value = Value(214, "shared_folders")
  val SHARED_MEMORY: FleetTables.Value = Value(215, "shared_memory")
  val SHARED_RESOURCES: FleetTables.Value = Value(216, "shared_resources")
  val SHARING_PREFERENCES: FleetTables.Value = Value(217, "sharing_preferences")
  val SHELL_HISTORY: FleetTables.Value = Value(218, "shell_history")
  val SHELLBAGS: FleetTables.Value = Value(219, "shellbags")
  val SHIMCACHE: FleetTables.Value = Value(220, "shimcache")
  val SIGNATURE: FleetTables.Value = Value(221, "signature")
  val SIP_CONFIG: FleetTables.Value = Value(222, "sip_config")
  val SMART_DRIVE_INFO: FleetTables.Value = Value(223, "smart_drive_info")
  val SMBIOS_TABLES: FleetTables.Value = Value(224, "smbios_tables")
  val SMC_KEYS: FleetTables.Value = Value(225, "smc_keys")
  val SOCKET_EVENTS: FleetTables.Value = Value(226, "socket_events")
  val SSH_CONFIGS: FleetTables.Value = Value(227, "ssh_configs")
  val STARTUP_ITEMS: FleetTables.Value = Value(228, "startup_items")
  val SUDOERS: FleetTables.Value = Value(229, "sudoers")
  val SUID_BIN: FleetTables.Value = Value(230, "suid_bin")
  val SYSLOG_EVENTS: FleetTables.Value = Value(231, "syslog_events")
  val SYSTEM_CONTROLS: FleetTables.Value = Value(232, "system_controls")
  val SYSTEM_EXTENSIONS: FleetTables.Value = Value(233, "system_extensions")
  val SYSTEM_INFO: FleetTables.Value = Value(234, "system_info")
  val SYSTEMD_UNITS: FleetTables.Value = Value(235, "systemd_units")
  val TEMPERATURE_SENSORS: FleetTables.Value = Value(236, "temperature_sensors")
  val TIME: FleetTables.Value = Value(237, "time")
  val TIME_MACHINE_BACKUPS: FleetTables.Value = Value(238, "time_machine_backups")
  val TIME_MACHINE_DESTINATIONS: FleetTables.Value = Value(239, "time_machine_destinations")
  val ULIMIT_INFO: FleetTables.Value = Value(240, "ulimit_info")
  val UPTIME: FleetTables.Value = Value(241, "uptime")
  val USB_DEVICES: FleetTables.Value = Value(242, "usb_devices")
  val USER_EVENTS: FleetTables.Value = Value(243, "user_events")
  val USER_GROUPS: FleetTables.Value = Value(244, "user_groups")
  val USER_INTERACTION_EVENTS: FleetTables.Value = Value(245, "user_interaction_events")
  val USER_SSH_KEYS: FleetTables.Value = Value(246, "user_ssh_keys")
  val USERASSIST: FleetTables.Value = Value(247, "userassist")
  val USERS: FleetTables.Value = Value(248, "users")
  val VIDEO_INFO: FleetTables.Value = Value(249, "video_info")
  val VIRTUAL_MEMORY_INFO: FleetTables.Value = Value(250, "virtual_memory_info")
  val WIFI_NETWORKS: FleetTables.Value = Value(251, "wifi_networks")
  val WIFI_STATUS: FleetTables.Value = Value(252, "wifi_status")
  val WIFI_SURVEY: FleetTables.Value = Value(253, "wifi_survey")
  val WINBASEOBJ: FleetTables.Value = Value(254, "winbaseobj")
  val WINDOWS_CRASHES: FleetTables.Value = Value(255, "windows_crashes")
  val WINDOWS_EVENTLOG: FleetTables.Value = Value(256, "windows_eventlog")
  val WINDOWS_EVENTS: FleetTables.Value = Value(257, "windows_events")
  val WINDOWS_OPTIONAL_FEATURES: FleetTables.Value = Value(258, "windows_optional_features")
  val WINDOWS_SECURITY_CENTER: FleetTables.Value = Value(259, "windows_security_center")
  val WINDOWS_SECURITY_PRODUCTS: FleetTables.Value = Value(260, "windows_security_products")
  val WMI_BIOS_INFO: FleetTables.Value = Value(261, "wmi_bios_info")
  val WMI_CLI_EVENT_CONSUMERS: FleetTables.Value = Value(262, "wmi_cli_event_consumers")
  val WMI_EVENT_FILTERS: FleetTables.Value = Value(263, "wmi_event_filters")
  val WMI_FILTER_CONSUMER_BINDING: FleetTables.Value = Value(264, "wmi_filter_consumer_binding")
  val WMI_SCRIPT_EVENT_CONSUMERS: FleetTables.Value = Value(265, "wmi_script_event_consumers")
  val XPROTECT_ENTRIES: FleetTables.Value = Value(266, "xprotect_entries")
  val XPROTECT_META: FleetTables.Value = Value(267, "xprotect_meta")
  val XPROTECT_REPORTS: FleetTables.Value = Value(268, "xprotect_reports")
  val YARA: FleetTables.Value = Value(269, "yara")
  val YARA_EVENTS: FleetTables.Value = Value(270, "yara_events")
  val YCLOUD_INSTANCE_METADATA: FleetTables.Value = Value(271, "ycloud_instance_metadata")
  val YUM_SOURCES: FleetTables.Value = Value(272, "yum_sources")
  /*
   * The list of Osquery tables (version 4.6.0) is extended
   * by a proprietary `osquery_status` table to also take
   * status log event into account
   *
   */
  val OSQUERY_STATUS: FleetTables.Value = Value(273, "osquery_status")

}
