-- Copyright 2004-2018 H2 Group. Multiple-Licensed under the MPL 2.0,
-- and the EPL 1.0 (http://h2database.com/html/license.html).
-- Initial Developer: H2 Group
--

CREATE SCHEMA TEST_SCHEMA;
> ok

DROP SCHEMA TEST_SCHEMA RESTRICT;
> ok

CREATE SCHEMA TEST_SCHEMA;
> ok

CREATE TABLE TEST_SCHEMA.TEST();
> ok

DROP SCHEMA TEST_SCHEMA RESTRICT;
> exception

DROP SCHEMA TEST_SCHEMA CASCADE;
> ok

CREATE SCHEMA TEST_SCHEMA;
> ok

CREATE VIEW TEST_SCHEMA.TEST AS SELECT 1;
> ok

DROP SCHEMA TEST_SCHEMA RESTRICT;
> exception

DROP SCHEMA TEST_SCHEMA CASCADE;
> ok

CREATE TABLE PUBLIC.SRC();
> ok

CREATE SCHEMA TEST_SCHEMA;
> ok

CREATE SYNONYM TEST_SCHEMA.TEST FOR PUBLIC.SRC;
> ok

DROP SCHEMA TEST_SCHEMA RESTRICT;
> exception

DROP SCHEMA TEST_SCHEMA CASCADE;
> ok

DROP TABLE PUBLIC.SRC;
> ok

CREATE SCHEMA TEST_SCHEMA;
> ok

CREATE SEQUENCE TEST_SCHEMA.TEST;
> ok

DROP SCHEMA TEST_SCHEMA RESTRICT;
> exception

DROP SCHEMA TEST_SCHEMA CASCADE;
> ok

CREATE SCHEMA TEST_SCHEMA;
> ok

CREATE CONSTANT TEST_SCHEMA.TEST VALUE 1;
> ok

DROP SCHEMA TEST_SCHEMA RESTRICT;
> exception

DROP SCHEMA TEST_SCHEMA CASCADE;
> ok

CREATE SCHEMA TEST_SCHEMA;
> ok

CREATE ALIAS TEST_SCHEMA.TEST FOR "java.lang.System.currentTimeMillis";
> ok

DROP SCHEMA TEST_SCHEMA RESTRICT;
> exception

DROP SCHEMA TEST_SCHEMA CASCADE;
> ok
