/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// README.txt generation entry point.
$generatorReadme = {};

/**
 * Generate README.txt.
 *
 * @param res Resulting output with generated readme.
 * @returns {string} Generated content.
 */
$generatorReadme.readme = function (res) {
    if (!res)
        res = $generatorCommon.builder();

    res.line('Content of this folder was generated by Apache Ignite Web Console');
    res.line('=================================================================');

    res.needEmptyLine = true;

    res.line('Ignite ships with CacheJdbcPojoStore, which is out-of-the-box JDBC');
    res.line('implementation of the IgniteCacheStore interface, and automatically');
    res.line('handles all the write-through and read-through logic.');

    res.needEmptyLine = true;

    res.line('You can use generated configuration and POJO classes as part of your application.');

    res.needEmptyLine = true;

    res.line('Note, in case of using proprietary JDBC drivers (Oracle, IBM DB2, Microsoft SQL Server)');
    res.line('you should download them and copy into ./jdbc-drivers folder.');

    return res;
};

/**
 * Generate README.txt for jdbc folder.
 *
 * @param res Resulting output with generated readme.
 * @returns {string} Generated content.
 */
$generatorReadme.readmeJdbc = function (res) {
    if (!res)
        res = $generatorCommon.builder();

    res.line('Copy proprietary JDBC drivers to this folder.');

    return res;
};
