/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.ignite.internal.processors.metastorage.persistence;

import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import org.apache.ignite.internal.dto.IgniteDataTransferObjectSerializer;
import org.apache.ignite.internal.util.typedef.internal.U;

/**
 * This class is implements {@link IgniteDataTransferObjectSerializer}.
 * Most implementation of the interface autogenerated.
 * <b>Please, be aware - serializer works while Rolling Upgrade in progress.</b>
 * All changes must be made with the respece of RU rules.
 * <b>
 *     Note, this class written in PDS!
 *     All versions of PDS must be compatible!
 *     Be extremely cautious when change.
 * </b>
 *
 * @see org.apache.ignite.internal.codegen.idto.IDTOSerializerFactory
 */
public class DistributedMetaStorageHistoryItemSerializer implements IgniteDataTransferObjectSerializer<DistributedMetaStorageHistoryItem> {
    /** {@inheritDoc} */
    @Override public void writeExternal(DistributedMetaStorageHistoryItem obj, ObjectOutput out) throws IOException {
        out.writeInt(obj.keys.length);

        for (int i = 0; i < obj.keys.length; i++) {
            U.writeString(out, obj.keys[i]);
            U.writeByteArray(out, obj.valBytesArr[i]);
        }
    }

    /** {@inheritDoc} */
    @Override public void readExternal(DistributedMetaStorageHistoryItem obj, ObjectInput in) throws IOException, ClassNotFoundException {
        int len = in.readInt();

        obj.keys = new String[len];
        obj.valBytesArr = new byte[len][];

        for (int i = 0; i < len; i++) {
            obj.keys[i] = U.readString(in);
            obj.valBytesArr[i] = U.readByteArray(in);
        }
    }
}
