/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.ignite.internal.binary;

import java.util.TreeMap;
import java.util.TreeSet;
import org.apache.ignite.internal.IgniteEx;
import org.apache.ignite.internal.processors.cache.binary.CacheObjectBinaryProcessorImpl;
import org.apache.ignite.internal.processors.closure.GridClosureProcessor;
import org.apache.ignite.internal.util.typedef.internal.U;
import org.apache.ignite.testframework.junits.common.GridCommonAbstractTest;
import org.junit.Test;

/**
 *
 */
public class BinaryContextPredefinedTypesTest extends GridCommonAbstractTest {
    /**
     * Tests that all predefined types have default constructor.
     */
    @Test
    public void testDefaultConstructor() {
        for (BinaryClassDescriptor desc : U.binaryContext(null).predefinedTypes()) {
            if (!desc.isBinary())
                continue;

            // Check that class descriptor uses default class constructor (not generated by U.ctorFactory()).
            // Ignite can't start if any predefined type misses default constructor and U.ctorFactory() is not available
            // (this can happens in some environments, for example, inside application server)
            assertTrue("Missing default constructor for predifined type " + desc.describedClass().getName(),
                desc.describedClass() == desc.ctor().getDeclaringClass());
        }
    }

    /**
     * Tests that binarylizable system classes registered by {@link BinaryContext} itself are cached in the registered
     * state, so a write does not rebuild the descriptor each time.
     */
    @Test
    public void testBinarilizableSystemClassesRegistered() {
        BinaryContext ctx = U.binaryContext(null);

        assertRegisteredSystemClass(ctx, TreeMap.class);
        assertRegisteredSystemClass(ctx, TreeSet.class);
        assertRegisteredSystemClass(ctx, BinaryTreeMap.class);
    }

    /**
     * Tests that binarylizable system classes registered by processors on node start are cached in the registered
     * state, so a write does not rebuild the descriptor each time.
     */
    @Test
    public void testProcessorBinarilizableSystemClassesRegistered() throws Exception {
        try {
            IgniteEx ignite = startGrid(0);

            BinaryContext ctx = ((CacheObjectBinaryProcessorImpl)ignite.context().cacheObjects()).binaryContext();

            assertRegisteredSystemClass(ctx, TreeMap.class);
            assertRegisteredSystemClass(ctx, TreeSet.class);
            assertRegisteredSystemClass(ctx, BinaryTreeMap.class);

            assertRegisteredSystemClass(ctx, GridClosureProcessor.C1.class);
            assertRegisteredSystemClass(ctx, GridClosureProcessor.C1MLA.class);
            assertRegisteredSystemClass(ctx, GridClosureProcessor.C2.class);
            assertRegisteredSystemClass(ctx, GridClosureProcessor.C2MLA.class);
            assertRegisteredSystemClass(ctx, GridClosureProcessor.C4.class);
            assertRegisteredSystemClass(ctx, GridClosureProcessor.C4MLA.class);
        }
        finally {
            stopAllGrids();
        }
    }

    /**
     * @param ctx Binary context.
     * @param cls System class to check.
     */
    private static void assertRegisteredSystemClass(BinaryContext ctx, Class<?> cls) {
        BinaryClassDescriptor desc = ctx.descriptorForClass(cls);

        assertFalse(cls.getName(), desc.userType());
        assertTrue("Cached descriptor must be registered: " + cls.getName(), desc.registered());

        // The write path must reuse the cached descriptor instead of creating a registered copy on every call.
        assertTrue("Write path must reuse cached descriptor: " + cls.getName(), desc == ctx.registerClass(cls, true, false));
    }
}
