# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "https://rubygems.org"

# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'asciidoctor'
gem 'jekyll', group: :jekyll_plugins
gem 'wdm', '~> 0.1.1' if Gem.win_platform?
group :jekyll_plugins do
  gem 'jekyll-asciidoc'
end
#gem 'pygments.rb', '~> 1.2.1'
gem 'thread_safe', '~> 0.3.6'
gem 'slim', '~> 4.0.1'
gem 'tilt', '~> 2.0.9'
