extends:
  - airbnb-base
  - plugin:unicorn/all
parser: '@babel/eslint-parser'
parserOptions:
  requireConfigFile: false
  sourceType: module
env:
  node: true
  es6: true
plugins:
  - import
rules:
  strict: [error, global]
  global-require: off
  func-names: off
  new-cap: off
  consistent-return: off
  no-console: off
  vars-on-top: off
  no-param-reassign: off
  prefer-arrow-callback: off
  no-nested-ternary: off

  no-restricted-syntax: off
  no-mixed-operators: off
  no-plusplus: off
  guard-for-in: off
  no-continue: off

  no-multi-spaces: off
  max-len: [error, 150, 2]
  prefer-template: off
  no-underscore-dangle: off

  import/extensions: [error, always]
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
      - '**/test/**/*.js'
      - '**/scripts/*.js'
      - '**/webpack.config.mjs'

  unicorn/filename-case: off
  unicorn/no-array-callback-reference: off
  unicorn/no-array-method-this-argument: off
  unicorn/no-keyword-prefix: off
  unicorn/no-null: off
  unicorn/no-unsafe-regex: off
  unicorn/numeric-separators-style: off
  unicorn/prefer-export-from: off
  unicorn/prevent-abbreviations: off

  # To be turned on
  no-shadow:
    - off
    - allow: [err, error]
