nodeLinker: node-modules

packageExtensions:
  '@cypress/code-coverage@*':
    peerDependencies:
      '@babel/core': '*'
      '@babel/preset-env': '*'
      'babel-loader': '*'
      'webpack': '*'

yarnPath: .yarn/releases/yarn-4.0.0-rc.26.cjs
