compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - checksum: 7930a64ba6239d4502df0204edda913788df1a9614a9056d23b53345d844f6f13526dae71c2be5282071502c3c077db7b1e97bcf019037db3ca35c737cd25b0c
    path: .yarn/plugins/plugin-dedupe-on-install.cjs
    spec: "https://raw.githubusercontent.com/ambar/yarn-plugin-dedupe-on-install/main/index.js"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
