

export const CONFIRM_CLUSTERS_REMOVAL = 'CONFIRM_CLUSTERS_REMOVAL';
export const CONFIRM_CLUSTERS_REMOVAL_OK = 'CONFIRM_CLUSTERS_REMOVAL_OK';
export const REMOVE_CLUSTER_ITEMS = 'REMOVE_CLUSTER_ITEMS';
export const REMOVE_CLUSTER_ITEMS_CONFIRMED = 'REMOVE_CLUSTER_ITEMS_CONFIRMED';
export const ADVANCED_SAVE_COMPLETE_CONFIGURATION = 'ADVANCED_SAVE_COMPLETE_CONFIGURATION';
export const ADVANCED_SAVE_COMPLETE_CONFIGURATION_OK = 'ADVANCED_SAVE_COMPLETE_CONFIGURATION_OK';
export const ADVANCED_SAVE_COMPLETE_CONFIGURATION_ERR = 'ADVANCED_SAVE_COMPLETE_CONFIGURATION_ERR';
export const COMPLETE_CONFIGURATION = 'COMPLETE_CONFIGURATION';
export const ADVANCED_SAVE_CLUSTER = 'ADVANCED_SAVE_CLUSTER';
export const ADVANCED_SAVE_CACHE = 'ADVANCED_SAVE_CACHE';
export const ADVANCED_SAVE_MODEL = 'ADVANCED_SAVE_MODEL';
export const ADVANCED_SAVE_IGFS = 'ADVANCED_SAVE_IGFS';
export const BASIC_SAVE = 'BASIC_SAVE';
export const BASIC_SAVE_AND_DOWNLOAD = 'BASIC_SAVE_AND_DOWNLOAD';
export const BASIC_SAVE_OK = 'BASIC_SAVE_OK';
export const BASIC_SAVE_ERR = 'BASIC_SAVE_ERR';
