/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.ignite.internal.managers.systemview.walker;

import org.apache.ignite.internal.processors.query.h2.database.H2IndexType;
import org.apache.ignite.spi.systemview.view.SqlIndexView;
import org.apache.ignite.spi.systemview.view.SystemViewRowAttributeWalker;

/**
 * Generated by {@code org.apache.ignite.codegen.SystemViewRowAttributeWalkerGenerator}.
 * {@link SqlIndexView} attributes walker.
 * 
 * @see SqlIndexView
 */
public class SqlIndexViewWalker implements SystemViewRowAttributeWalker<SqlIndexView> {
    /** {@inheritDoc} */
    @Override public void visitAll(AttributeVisitor v) {
        v.accept(0, "indexName", String.class);
        v.accept(1, "indexType", H2IndexType.class);
        v.accept(2, "columns", String.class);
        v.accept(3, "schemaName", String.class);
        v.accept(4, "tableName", String.class);
        v.accept(5, "cacheName", String.class);
        v.accept(6, "cacheId", int.class);
        v.accept(7, "inlineSize", int.class);
        v.accept(8, "isPk", boolean.class);
        v.accept(9, "isUnique", boolean.class);
    }

    /** {@inheritDoc} */
    @Override public void visitAll(SqlIndexView row, AttributeWithValueVisitor v) {
        v.accept(0, "indexName", String.class, row.indexName());
        v.accept(1, "indexType", H2IndexType.class, row.indexType());
        v.accept(2, "columns", String.class, row.columns());
        v.accept(3, "schemaName", String.class, row.schemaName());
        v.accept(4, "tableName", String.class, row.tableName());
        v.accept(5, "cacheName", String.class, row.cacheName());
        v.acceptInt(6, "cacheId", row.cacheId());
        v.acceptInt(7, "inlineSize", row.inlineSize());
        v.acceptBoolean(8, "isPk", row.isPk());
        v.acceptBoolean(9, "isUnique", row.isUnique());
    }

    /** {@inheritDoc} */
    @Override public int count() {
        return 10;
    }
}
