// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
= Control Script


Ignite provides a command line script — `control.sh|bat` — that you can use to monitor and control your clusters.
The script is located under the `/bin/` folder of the installation directory.

The control script syntax is as follows:

[tabs]
--
tab:Unix[]
[source, shell]
----
control.sh <connection parameters> <command> <arguments>
----
tab:Windows[]
[source, shell]
----
control.bat <connection parameters> <command> <arguments>
----
--

== Connecting to Cluster

NOTE: Starting from Apache Ignite version 2.17, the utility by default uses a connection through the thin client protocol (configured on a node via `org.apache.ignite.configuration.ClientConnectorConfiguration`). See link:#migration-to-the-thin-client-protocol[Migration Notes] for more information.

When executed without connection parameters, the control script tries to connect to a node running on localhost (`localhost:10800`).
If you want to connect to a node that is running on a remove machine, specify the connection parameters.

[cols="2,3,1",opts="header"]
|===
|Parameter | Description | Default Value
| --host HOST_OR_IP | The host name or IP address of the node. | `localhost`
| --port PORT | The port to connect to. | `10800`
| --user USER | The user name. |
| --password | Force `control.sh` to prompt for a user password before connecting to a cluster. Although you can explicitly specify a value for this option like `--password PASSWORD`, doing so is strongly discouraged due to security concerns. If this option is omitted, `control.sh` will automatically prompt for a user password if the server requires password authentication. However, `control.sh` will waste a connection attempt while determining whether the server needs a password. |
| --ssl-protocol PROTOCOL1, PROTOCOL2... | A list of SSL protocols to try when connecting to the cluster. link:https://docs.oracle.com/en/java/javase/11/security/java-security-overview1.html#GUID-FCF419A7-B856-46DD-A36F-C6F88F9AF37F[Supported protocols,window=_blank]. | `TLS`
| --ssl-cipher-suites CIPHER1,CIPHER2...  | A list of SSL ciphers. link:https://docs.oracle.com/en/java/javase/11/docs/specs/security/standard-names.html#jsse-cipher-suite-names[Supported ciphers,window=_blank]. |
| --ssl-key-algorithm ALG | The SSL key algorithm. | `SunX509`
| --keystore-type KEYSTORE_TYPE | The keystore type. | `JKS`
| --keystore KEYSTORE_PATH | The path to the keystore. Specify a keystore to enable SSL for the control script.|
| --keystore-password | Force `control.sh` to prompt for a keystore password before connecting to a cluster. Although you can explicitly specify a value for this option like `--keystore-password KEYSTORE_PWD`, doing so is strongly discouraged due to security concerns. If this option is omitted, `control.sh` will automatically prompt for a keystore password before connecting to the cluster if `--keystore KEYSTORE_PATH` argument is specified. |
| --truststore-type TRUSTSTORE_TYPE | The type of the truststore. | `JKS`
| --truststore TRUSTSTORE_PATH | The path to the truststore. |
| --truststore-password | Force `control.sh` to prompt for a truststore password before connecting to a cluster. Although you can explicitly specify a value for this option like `--truststore-password TRUSTSTORE_PWD`, doing so is strongly discouraged due to security concerns. If this option is omitted, `control.sh` will automatically prompt for a truststore password before connecting to the cluster if `--truststore TRUSTSTORE_PATH` argument is specified. |
| --ssl-factory SSL_FACTORY_PATH | Custom SSL factory Spring xml file path. |
|===

== Migration to the thin client protocol

With the default configuration of Ignite, no migration actions will be required. Additional configuration of the connector is no longer necessary.

If you connect to the wrong connector, you will receive an error and may see the message:

`Make sure you are connecting to the client connector (configured on a node via 'org.apache.ignite.configuration.ClientConnectorConfiguration'). Connection to the REST connector was deprecated and will be removed for the control utility in future releases. Set up the 'IGNITE_CONTROL_UTILITY_USE_CONNECTOR_CONNECTION' system property to 'true' to forcefully connect to the REST connector (configured on a node via 'org.apache.ignite.configuration.ConnectorConfiguration').`

To ensure backward compatibility, a system property has been added to provide the old behavior (note: it will be removed in version 2.18):

[tabs]
--
tab:Unix[]
[source, shell]
----
export IGNITE_CONTROL_UTILITY_USE_CONNECTOR_CONNECTION=true;
control.sh --state --host x.x.x.x --port 11212
----
tab:Windows[]
[source, shell]
----
SET IGNITE_CONTROL_UTILITY_USE_CONNECTOR_CONNECTION=true
control.bat --state --host x.x.x.x --port 11212
----
--

In some cases, the following actions may be required to migrate user scripts using the utility:

=== 1. A custom port is specified:

[tabs]
--
tab:Unix[]
[source, shell]
----
control.sh --state --host x.x.x.x --port 11212
----
tab:Windows[]
[source, shell]
----
control.bat --state --host x.x.x.x --port 11212
----
--

To migrate, specify the port for the thin client connector:

[tabs]
--
tab:Unix[]
[source, shell]
----
control.sh --state --host x.x.x.x
control.sh --state --host x.x.x.x --port 10801
----
tab:Windows[]
[source, shell]
----
control.bat --state --host x.x.x.x
control.bat --state --host x.x.x.x --port 10801
----
--

=== 2. A custom SSL factory for the binary REST connector is specified, different from the SSL factory for the thin client connector:

[tabs]
--
tab:Unix[]
[source, shell]
----
control.sh --state --ssl-factory connector-ssl-factory.xml
----
tab:Windows[]
[source, shell]
----
control.bat --state --ssl-factory connector-ssl-factory.xml
----
--

To migrate, specify the SSL factory for the thin client connector:

[tabs]
--
tab:Unix[]
[source, shell]
----
control.sh --state --ssl-factory ignite-ssl-factory.xml
control.sh --state --ssl-factory client-connector-ssl-factory.xml
----
tab:Windows[]
[source, shell]
----
control.bat --state --ssl-factory ignite-ssl-factory.xml
control.bat --state --ssl-factory client-connector-ssl-factory.xml
----
--

=== 3. The client connector is disabled.

Enable it in the configuration (`IgniteConfiguration#setClientConnectorConfiguration`).

== Activation, Deactivation and Topology Management

You can use the control script to activate or deactivate your cluster, and manage the link:clustering/baseline-topology[Baseline Topology].


=== Getting Cluster State

The cluster can be in one of the three states: active, read only, or inactive. Refer to link:monitoring-metrics/cluster-states[Cluster States] for details.

To get the state of the cluster, run the following command:

[tabs]
--
tab:Unix[]
[source,shell,subs="verbatim,quotes"]
----
control.sh --state
----
tab:Windows[]
[source,shell,subs="verbatim,quotes"]
----
control.bat --state
----
--

=== Activating Cluster

Activation sets the baseline topology of the cluster to the set of nodes available at the moment of activation.
Activation is required only if you use link:persistence/native-persistence[native persistence].

To activate the cluster, run the following command:

[tabs]
--
tab:Unix[]
[source,shell,subs="verbatim,quotes"]
----
control.sh --set-state ACTIVE
----
tab:Windows[]
[source,shell,subs="verbatim,quotes"]
----
control.bat --set-state ACTIVE
----
--

=== Deactivating Cluster

include::includes/note-on-deactivation.adoc[]

To deactivate the cluster, run the following command:

[tabs]
--
tab:Unix[]
[source,shell,subs="verbatim,quotes"]
----
control.sh --set-state INACTIVE [--yes]
----
tab:Windows[]
[source,shell,subs="verbatim,quotes"]
----
control.bat --set-state INACTIVE [--yes]
----
--



=== Getting Nodes Registered in Baseline Topology

To get the list of nodes registered in the baseline topology, run the following command:

[tabs]
--
tab:Unix[]
[source,shell,subs="verbatim,quotes"]
----
control.sh --baseline
----

tab:Windows[]
[source,shell,subs="verbatim,quotes"]
----
control.bat --baseline
----
--

The output contains the current topology version, the list of consistent IDs of the nodes included in the baseline topology, and the list of nodes that joined the cluster but were not added to the baseline topology.

[source, shell]
----
Command [BASELINE] started
Arguments: --baseline
--------------------------------------------------------------------------------
Cluster state: active
Current topology version: 3

Current topology version: 3 (Coordinator: ConsistentId=dd3d3959-4fd6-4dc2-8199-bee213b34ff1, Order=1)

Baseline nodes:
    ConsistentId=7d79a1b5-cbbd-4ab5-9665-e8af0454f178, State=ONLINE, Order=2
    ConsistentId=dd3d3959-4fd6-4dc2-8199-bee213b34ff1, State=ONLINE, Order=1
--------------------------------------------------------------------------------
Number of baseline nodes: 2

Other nodes:
    ConsistentId=30e16660-49f8-4225-9122-c1b684723e97, Order=3
Number of other nodes: 1
Command [BASELINE] finished with code: 0
Control utility has completed execution at: 2019-12-24T16:53:08.392865
Execution time: 333 ms
----

=== Adding Nodes to Baseline Topology

To add a node to the baseline topology, run the command given below.
After the node is added, the link:data-rebalancing[rebalancing process] starts.

[tabs]
--
tab:Unix[]
[source,shell,subs="verbatim,quotes"]
----
control.sh --baseline add _consistentId1,consistentId2,..._ [--yes]
----
tab:Windows[]
[source,shell,subs="verbatim,quotes"]
----
control.bat --baseline add _consistentId1,consistentId2,..._ [--yes]
----
--

=== Removing Nodes from Baseline Topology

To remove a node from the baseline topology, use the `remove` command.
Only offline nodes can be removed from the baseline topology: shut down the node first and then use the `remove` command.
This operation starts the rebalancing process, which re-distributes the data across the nodes that remain in the baseline topology.

[tabs]
--
tab:Unix[]
[source,shell,subs="verbatim,quotes"]
----
control.sh --baseline remove _consistentId1,consistentId2,..._ [--yes]
----
tab:Windows[]
[source,shell,subs="verbatim,quotes"]
----
control.bat --baseline remove _consistentId1,consistentId2,..._ [--yes]
----
--

=== Setting Baseline Topology

You can set the baseline topology by either providing a list of nodes (consistent IDs) or by specifying the desired version of the baseline topology.

To set a list of node as the baseline topology, use the following command:

[tabs]
--
tab:Unix[]

[source,shell,subs="verbatim,quotes"]
----
control.sh --baseline set _consistentId1,consistentId2,..._ [--yes]
----
tab:Windows[]
[source,shell,subs="verbatim,quotes"]
----
control.bat --baseline set _consistentId1,consistentId2,..._ [--yes]
----
--


To restore a specific version of the baseline topology, use the following command:

[tabs]
--
tab:Unix[]
[source,shell,subs="verbatim,quotes"]
----
control.sh --baseline version _topologyVersion_ [--yes]
----
tab:Windows[]
[source,shell,subs="verbatim,quotes"]
----
control.bat --baseline version _topologyVersion_ [--yes]
----
--

=== Enabling Baseline Topology Autoadjustment

link:clustering/baseline-topology#baseline-topology-autoadjustment[Baseline topology autoadjustment] refers to automatic update of baseline topology after the topology has been stable for a specific amount of time.

For in-memory clusters, autoadjustment is enabled by default with the timeout set to 0. It means that baseline topology changes immediately after server nodes join or leave the cluster.
For clusters with persistence, the automatic baseline adjustment is disabled by default.
To enable it, use the following command:

[tabs]
--
tab:Unix[]

[source, shell]
----
control.sh --baseline auto_adjust enable timeout 30000
----
tab:Windows[]
[source, shell]
----
control.bat --baseline auto_adjust enable timeout 30000
----
--

The timeout is set in milliseconds. The baseline is set to the current topology when a given number of milliseconds has passed after the last JOIN/LEFT/FAIL event.
Every new JOIN/LEFT/FAIL event restarts the timeout countdown.

To disable baseline autoadjustment, use the following command:

[tabs]
--
tab:Unix[]

[source, shell]
----
control.sh --baseline auto_adjust disable
----
tab:Windows[]
[source, shell]
----
control.bat --baseline auto_adjust disable
----
--


== Transaction Management

The control script allows you to get the information about the transactions being executed in the cluster.
You can also cancel specific transactions.

The following command returns a list of transactions that satisfy a given filter (or all transactions if no filter is provided):
[tabs]
--
tab:Unix[]
[source,shell,subs="verbatim,quotes"]
----
control.sh --tx _<transaction filter>_ --info
----
tab:Windows[]
[source,shell,subs="verbatim,quotes"]
----
control.bat --tx _<transaction filter>_ --info
----
--

The transaction filter parameters are listed in the following table.

[cols="2,5",opts="header"]
|===
|Parameter | Description
| --xid _XID_ | Transaction ID.
| --min-duration _SECONDS_ | Minimum number of seconds a transaction has been executing.
|--min-size _SIZE_ | Minimum size of a transaction
|--label _LABEL_ | User label for transactions. You can use a regular expression.
|--servers\|--clients | Limit the scope of the operation to either server or client nodes.
| --nodes _nodeId1,nodeId2..._ |  The list of consistent IDs of the nodes you want to get transactions from.
|--limit _NUMBER_ | Limit the number of transactions to the given value.
|--order DURATION\|SIZE\|START_TIME | The parameter that is used to sort the output.
|===


To cancel transactions, use the following command:

[tabs]
--
tab:Unix[]
[source,shell,subs="verbatim,quotes"]
----
control.sh --tx _<transaction filter>_ --kill
----
tab:Windows[]
[source,shell,subs="verbatim,quotes"]
----
control.bat --tx _<transaction filter>_ --kill
----
--

For example, to cancel the transactions that have been running for more than 100 seconds, execute the following command:

[source, shell]
----
control.sh --tx --min-duration 100 --kill
----

== Contention Detection in Transactions

The `contention` command detects when multiple transactions are in contention to create a lock for the same key. The command is useful if you have long-running or hanging transactions.

Example:

[tabs]
--
tab:Shell[]
[source,shell]
----
# Reports all keys that are point of contention for at least 5 transactions on all cluster nodes.
control.sh|bat --cache contention 5

# Reports all keys that are point of contention for at least 5 transactions on specific server node.
control.sh|bat --cache contention 5 f2ea-5f56-11e8-9c2d-fa7a
----
--

If there are any highly contended keys, the utility dumps extensive information including the keys, transactions, and nodes where the contention took place.

Example:

[source,text]
----
[node=TcpDiscoveryNode [id=d9620450-eefa-4ab6-a821-644098f00001, addrs=[127.0.0.1], sockAddrs=[/127.0.0.1:47501], discPort=47501, order=2, intOrder=2, lastExchangeTime=1527169443913, loc=false, ver=2.5.0#20180518-sha1:02c9b2de, isClient=false]]

// No contention on node d9620450-eefa-4ab6-a821-644098f00001.

[node=TcpDiscoveryNode [id=03379796-df31-4dbd-80e5-09cef5000000, addrs=[127.0.0.1], sockAddrs=[/127.0.0.1:47500], discPort=47500, order=1, intOrder=1, lastExchangeTime=1527169443913, loc=false, ver=2.5.0#20180518-sha1:02c9b2de, isClient=false]]
    TxEntry [cacheId=1544803905, key=KeyCacheObjectImpl [part=0, val=0, hasValBytes=false], queue=10, op=CREATE, val=UserCacheObjectImpl [val=0, hasValBytes=false], tx=GridNearTxLocal[xid=e9754629361-00000000-0843-9f61-0000-000000000001, xidVersion=GridCacheVersion [topVer=138649441, order=1527169439646, nodeOrder=1], concurrency=PESSIMISTIC, isolation=REPEATABLE_READ, state=ACTIVE, invalidate=false, rollbackOnly=false, nodeId=03379796-df31-4dbd-80e5-09cef5000000, timeout=0, duration=1247], other=[]]
    TxEntry [cacheId=1544803905, key=KeyCacheObjectImpl [part=0, val=0, hasValBytes=false], queue=10, op=READ, val=null, tx=GridNearTxLocal[xid=8a754629361-00000000-0843-9f61-0000-000000000001, xidVersion=GridCacheVersion [topVer=138649441, order=1527169439656, nodeOrder=1], concurrency=PESSIMISTIC, isolation=REPEATABLE_READ, state=ACTIVE, invalidate=false, rollbackOnly=false, nodeId=03379796-df31-4dbd-80e5-09cef5000000, timeout=0, duration=1175], other=[]]
    TxEntry [cacheId=1544803905, key=KeyCacheObjectImpl [part=0, val=0, hasValBytes=false], queue=10, op=READ, val=null, tx=GridNearTxLocal[xid=6a754629361-00000000-0843-9f61-0000-000000000001, xidVersion=GridCacheVersion [topVer=138649441, order=1527169439654, nodeOrder=1], concurrency=PESSIMISTIC, isolation=REPEATABLE_READ, state=ACTIVE, invalidate=false, rollbackOnly=false, nodeId=03379796-df31-4dbd-80e5-09cef5000000, timeout=0, duration=1175], other=[]]
    TxEntry [cacheId=1544803905, key=KeyCacheObjectImpl [part=0, val=0, hasValBytes=false], queue=10, op=READ, val=null, tx=GridNearTxLocal[xid=7a754629361-00000000-0843-9f61-0000-000000000001, xidVersion=GridCacheVersion [topVer=138649441, order=1527169439655, nodeOrder=1], concurrency=PESSIMISTIC, isolation=REPEATABLE_READ, state=ACTIVE, invalidate=false, rollbackOnly=false, nodeId=03379796-df31-4dbd-80e5-09cef5000000, timeout=0, duration=1175], other=[]]
    TxEntry [cacheId=1544803905, key=KeyCacheObjectImpl [part=0, val=0, hasValBytes=false], queue=10, op=READ, val=null, tx=GridNearTxLocal[xid=4a754629361-00000000-0843-9f61-0000-000000000001, xidVersion=GridCacheVersion [topVer=138649441, order=1527169439652, nodeOrder=1], concurrency=PESSIMISTIC, isolation=REPEATABLE_READ, state=ACTIVE, invalidate=false, rollbackOnly=false, nodeId=03379796-df31-4dbd-80e5-09cef5000000, timeout=0, duration=1175], other=[]]

// Node 03379796-df31-4dbd-80e5-09cef5000000 is place for contention on key KeyCacheObjectImpl [part=0, val=0, hasValBytes=false].
----


== Monitoring Cache State

One of the most important commands that `control.sh|bat` provides is `--cache list`, which is used for cache monitoring. The command provides a list of deployed caches and their affinity/distributiong parameters and distribution within cache groups. There is also a command for viewing existing atomic sequences.

[source,shell]
----
# Displays a list of all caches
control.sh|bat --cache list .

# Displays a list of caches whose names start with "account-".
control.sh|bat --cache list account-.*

# Displays info about cache group distribution for all caches.
control.sh|bat --cache list . --groups

# Displays info about cache group distribution for the caches whose names start with "account-".
control.sh|bat --cache list account-.* --groups

# Displays info about all atomic sequences.
control.sh|bat --cache list . --seq

# Displays info about the atomic sequnces whose names start with "counter-".
control.sh|bat --cache list counter-.* --seq
----

== Creating Caches

You can use the control script to create specific caches.

NOTE: The 'ignite-spring' module should be enabled.

[source, shell]
----
control.sh|bat --cache create --springXmlConfig springXmlFilePath --skip-existing
----

Parameters:

[cols="1,3",opts="header"]
|===
| Parameter | Description
| `--springXmlConfig springXmlConfigPath` | Path to the Spring XML configuration that contains
'org.apache.ignite.configuration.CacheConfiguration' beans to create caches from.
|`--skip-existing`| Optional flag to skip existing caches.
|===

Examples:
[source, shell]
----
# Create caches from the `/ignite/config/userCaches.xml` configuration.
control.sh|bat --cache create --springXmlConfig /ignite/config/userCaches.xml

# Create caches from the `/ignite/config/userCaches.xml` configuration except existing ones.
control.sh|bat --cache create --springXmlConfig /ignite/config/userCaches.xml --skip-existing
----

== Destroying Caches

You can use the control script to destroy specific caches.

[source, shell]
----
control.sh|bat --cache destroy --caches cache1,...,cacheN|--destroy-all-caches
----

Parameters:

[cols="1,3",opts="header"]
|===
| Parameter | Description
| `--caches cache1,...,cacheN`| Specifies a comma-separated list of cache names to be destroyed.
| `--destroy-all-caches` | Permanently destroy all user-created caches.
|===

Examples:
[source, shell]
----
# Destroy cache1 and cache2.
control.sh|bat --cache destroy --caches cache1,cache2

# Destroy all user-created caches.
control.sh|bat --cache destroy --destroy-all-caches
----

== Clearing Caches

You can use the control script to clear specific caches.

[source, shell]
----
control.sh|bat --cache clear --caches cache1,...,cacheN
----

Parameters:

[cols="1,3",opts="header"]
|===
| Parameter | Description
| `--caches cache1,...,cacheN`| Specifies a comma-separated list of cache names to be cleared.
|===

Examples:
[source, shell]
----
# Clear cache1 and cache2.
control.sh|bat --cache clear --caches cache1,cache2
----

== Scanning Caches

You can use the control script to scan cache entries.

[source, shell]
----
control.sh|bat --cache scan cacheName [--limit N]
----

For each entry four columns will be displayed: key class, string representation of key, value class, and string representation of value.

Parameters:

[cols="1,3",opts="header"]
|===
| Parameter | Description
| `--limit N`| Limit amount of entries to scan (default 1000).
|===

Examples:
[source, shell]
----
# Query no more than 10 entries from cache "cache1"
control.sh|bat --cache scan cache1 --limit 10
----

== Resetting Lost Partitions

You can use the control script to reset lost partitions for specific cache groups.
Refer to link:configuring-caches/partition-loss-policy[Partition Loss Policy] for details.

[source, shell]
----
control.sh --cache reset_lost_partitions cacheGroupName1,cacheGroupName2,...
----


== Consistency Check and Repair Commands

`control.sh|bat` includes a set of consistency check commands that enable you to verify and repair internal data consistency.

First, the commands can be used for debugging and troubleshooting purposes especially if you're in active development.

Second, if there is a suspicion that a query (such as a SQL query, etc.) returns an incomplete or wrong result set, the commands can verify whether there is inconsistency in the data.

Third, the consistency check commands can be utilized as a part of regular cluster health monitoring.

Finally, consistency can be repaired if necessary.

Let's review these usage scenarios in more detail.

=== Verifying Partition Checksums

Even if update counters and size are equal on the primary and backup nodes, the primary and backup might diverge due to some critical failure.

The `idle_verify` command compares the hash of the primary partition with that of the backup partitions and reports any differences.
The differences might be the result of node failure or incorrect shutdown during an update operation.

If any inconsistency is detected, we recommend removing the incorrect partitions or repairing the consistency using the `--consistency repair` command.

[source,shell]
----
# Checks partitions of all caches that their partitions actually contain same data.
control.sh|bat --cache idle_verify

# Checks partitions of specific caches that their partitions actually contain same data.
control.sh|bat --cache idle_verify cache1,cache2,cache3
----

If any partitions diverge, a list of conflict partitions is printed out, as follows:

[source,text]
----
idle_verify check has finished, found 2 conflict partitions.

Conflict partition: PartitionKey [grpId=1544803905, grpName=default, partId=5]
Partition instances: [PartitionHashRecord [isPrimary=true, partHash=97506054, updateCntr=3, size=3, consistentId=bltTest1], PartitionHashRecord [isPrimary=false, partHash=65957380, updateCntr=3, size=2, consistentId=bltTest0]]
Conflict partition: PartitionKey [grpId=1544803905, grpName=default, partId=6]
Partition instances: [PartitionHashRecord [isPrimary=true, partHash=97595430, updateCntr=3, size=3, consistentId=bltTest1], PartitionHashRecord [isPrimary=false, partHash=66016964, updateCntr=3, size=2, consistentId=bltTest0]]
----

[WARNING]
====
[discrete]
=== Cluster Should Be Idle During `idle_verify` Check
All updates should be stopped when `idle_verify` calculates hashes, otherwise it may show false positive error results. It's impossible to compare big datasets in a distributed system if they are being constantly updated​.
====

To cancel a running `idle_verify` operation, use the `--cancel` argument:

[source, shell]
----
control.sh --cache idle_verify --cancel
----

=== Repairing cache consistency
[WARNING]
====
[discrete]
===  Experimental feature
The command may not work on some special/unique configurations or even cause a cluster/node failure.

Command execution MUST be checked on the test environment using the data/configuration similar to the production before the execution on the real production environment.
====

`idle_verify` command provides the inconsistent cache group names and partitions list as a result.
The `repair` command allows performing cache consistency check and repair (when possible) using the link:key-value-api/read-repair[Read Repair] approach for every inconsistent partition found by `idle_verify`.

The command uses special strategies to perform the repair. It's recommended to use `CHECK_ONLY` strategy to list inconsistent values and then choose the proper link:key-value-api/read-repair#strategies[Repair Strategy].

By default, found inconsistent entries will be listed in the application log. You may change the location by configuring the logger for a special logging path for the `org.apache.ignite.internal.visor.consistency` package.

By default, found inconsistent entries will be listed as is but may be masked by enabling link:logging#suppressing-sensitive-information[IGNITE_TO_STRING_INCLUDE_SENSITIVE] system property.

[tabs]
--
tab:Unix[]
[source,shell]
----
control.sh --enable-experimental --consistency repair --cache cache-name --partitions partitions --strategy strategy
----
tab:Window[]
[source,shell]
----
control.bat --enable-experimental --consistency repair --cache cache-name --partitions partitions --strategy strategy
----
--
Parameters:

[cols="1,3",opts="header"]
|===
| Parameter | Description
| `cache-name`| Cache (or cache group) name to be checked/repaired.
| `partitions`| Comma separated list of cache's partitions to be checked/repaired.
| `strategy`| See link:key-value-api/read-repair#strategies[Repair Strategies].
|===

Optional parameters:

[cols="1,3",opts="header"]
|===
| Parameter | Description
| `--parallel`| Allows performing check/repair in the fastest way, by parallel execution at all partition owners.
|===

=== Cache consistency check/repair operations status

The command allows to check `--consistency repair` commands status.

[tabs]
--
tab:Unix[]
[source,shell]
----
control.sh --enable-experimental --consistency status
----
tab:Window[]
[source,shell]
----
control.bat --enable-experimental --consistency status
----
--

=== Partition update counters finalization

The command allows fo finalize partition update counters after the manual repair.
Finalization closes gaps at transactional cache partition update counters.

[tabs]
--
tab:Unix[]
[source,shell]
----
control.sh --enable-experimental --consistency finalize
----
tab:Window[]
[source,shell]
----
control.bat --enable-experimental --consistency finalize
----
--

=== Validating SQL Index Consistency
The `validate_indexes` command validates the indexes of given caches on all cluster nodes.

The following is checked by the validation process:

. All the key-value entries that are referenced from a primary index has to be reachable from secondary SQL indexes.
. All the key-value entries that are referenced from a primary index has to be reachable. A reference from the primary index shouldn't point to nowhere.
. All the key-value entries that are referenced from secondary SQL indexes have to be reachable from the primary index.

[tabs]
--
tab:Shell[]
[source,shell]
----
# Checks indexes of all caches on all cluster nodes.
control.sh|bat --cache validate_indexes

# Checks indexes of specific caches on all cluster nodes.
control.sh|bat --cache validate_indexes cache1,cache2

# Checks indexes of specific caches on node with given node ID.
control.sh|bat --cache validate_indexes cache1,cache2 f2ea-5f56-11e8-9c2d-fa7a
----
--

If indexes refer to non-existing entries (or some entries are not indexed), errors are dumped to the output, as follows:

[source,text]
----
PartitionKey [grpId=-528791027, grpName=persons-cache-vi, partId=0] ValidateIndexesPartitionResult [updateCntr=313, size=313, isPrimary=true, consistentId=bltTest0]
IndexValidationIssue [key=0, cacheName=persons-cache-vi, idxName=_key_PK], class org.apache.ignite.IgniteCheckedException: Key is present in CacheDataTree, but can't be found in SQL index.
IndexValidationIssue [key=0, cacheName=persons-cache-vi, idxName=PERSON_ORGID_ASC_IDX], class org.apache.ignite.IgniteCheckedException: Key is present in CacheDataTree, but can't be found in SQL index.
validate_indexes has finished with errors (listed above).
----

[WARNING]
====
[discrete]
=== Cluster Should Be Idle During `validate_indexes` Check
Like `idle_verify`, index validation tool works correctly only if updates are stopped. Otherwise, there may be a race between the checker thread and the thread that updates the entry/index, which can result in a false positive error report.
====

=== Checking Snapshot Consistency

The checking snapshot consistency command works the same way as the `idle_verify` command does. It compares hashes between
a primary partition and a corresponding backup partitions and prints a report if any differences are found.
Differences may be the result of inconsistencies in some data on the cluster from which the snapshot was taken. It is
recommended to perform the `idle_verify` procedure on the cluster if this case occurs.

The checking incremental snapshot command verifies data in WAL segments only. It checks that every transaction included into
snapshot is fully committed on every participated node. It also calculates hashes of these transactions and committed data
changes and compares it between nodes.

[WARNING]
====
[discrete]
=== The Incremental Snapshot Check verifies transactional caches only
Please note, incremental snapshots doesn't guarantee consistency of atomic caches. It is highly recommended verifying these
caches after restoring with the `idle_verify` command. If it is needed it's possible to repair inconsistent partitions with
the `--consistency` command.
====

This procedure does not require the cluster to be in the `idle` state.

[tabs]
--
tab:Shell[]
[source,shell]
----
# Checks that partitions of all snapshot caches have the correct checksums and primary/backup ones actually contain the same data.
control.(sh|bat) --snapshot check snapshot_name

# Checks the transactional data included into incremental snapshots. Incremental snapshots with indices from 1 to 3 are checked.
control.(sh|bat) --snapshot check snapshot_name --increment 3

----
--

=== Check SQL Index Inline Size

A running Ignite cluster could have different SQL index inline sizes on its cluster nodes.
For example, it could happen due to the `IGNITE_MAX_INDEX_PAYLOAD_SIZE` property value is different on the cluster nodes. The difference
between index inline sizes may lead to a performance drop.

The `check_index_inline_sizes` command validates the indexes inline size of given caches on all cluster nodes. The inline
size of secondary indexes is always checked on a node join and a WARN message is printed to the log if they differ.

Use the command below to check if the secondary indexes inline sizes are the same on all cluster nodes.

[tabs]
--
tab:Shell[]
[source,shell]
----
control.sh|bat --cache check_index_inline_sizes
----
--

If the index inline sizes are different, the console output is similar to the data below:

[source,text]
----
Control utility [ver. 2.10.0]
2022 Copyright(C) Apache Software Foundation
User: test
Time: 2021-04-27T16:13:21.213
Command [CACHE] started
Arguments: --cache check_index_inline_sizes --yes

Found 4 secondary indexes.
3 index(es) have different effective inline size on nodes. It can lead to
performance degradation in SQL queries.
Index(es):
  Full index name: PUBLIC#TEST_TABLE#L_IDX nodes:
[ca1d23ae-89d4-4e8d-ae12-6c68f3900000] inline size: 1, nodes:
[8327bbd1-df08-4b97-8721-de95e363e745] inline size: 2
  Full index name: PUBLIC#TEST_TABLE#S1_IDX nodes:
[ca1d23ae-89d4-4e8d-ae12-6c68f3900000] inline size: 1, nodes:
[8327bbd1-df08-4b97-8721-de95e363e745] inline size: 2
  Full index name: PUBLIC#TEST_TABLE#I_IDX nodes:
[ca1d23ae-89d4-4e8d-ae12-6c68f3900000] inline size: 1, nodes:
[8327bbd1-df08-4b97-8721-de95e363e745] inline size: 2
----

== Cluster ID and Tag

A cluster ID is a unique identifier of the cluster that is generated automatically when the cluster starts for the first time. Read link:monitoring-metrics/cluster-id[Cluster ID and Tag] for more information.

To view the cluster ID, run the `--state` command:

[tabs]
--
tab:Unix[]
[source,shell,subs="verbatim,quotes"]
----
control.sh --state
----
tab:Windows[]
[source,shell,subs="verbatim,quotes"]
----
control.bat --state
----
--

And check the output:

[source, text]
----
Command [STATE] started
Arguments: --state
--------------------------------------------------------------------------------
Cluster  ID: bf9764ea-995e-4ea9-b35d-8c6d078b0234
Cluster tag: competent_black
--------------------------------------------------------------------------------
Cluster is active
Command [STATE] finished with code: 0
----

A cluster tag is a user friendly name that you can assign to your cluster.
To change the tag, use the following command (the tag must contain no more than 280 characters):

[tabs]
--
tab:Unix[]
[source,shell,subs="verbatim,quotes"]
----
control.sh --change-tag _<new-tag>_
----
tab:Windows[]
[source,shell,subs="verbatim,quotes"]
----
control.bat --change-tag _<new-tag>_
----
--

== Metric Command

The metrics command prints out the value of a metric or metric registry provided in the parameters list. Use the `--node-id` parameter, If you need to get a metric from a specific node. Ignite selects a random node, if the `--node-id` is not set.

[tabs]
--
tab:Unix[]
[source,shell,subs="verbatim,quotes"]
----
control.sh --metric sys
----
tab:Windows[]
[source,shell,subs="verbatim,quotes"]
----
control.bat --metric sys
----
--

Example of the metric output:
[source, text]
control.sh --metric sysCurrentThreadCpuTime
Command [METRIC] started
Arguments: --metric sys
--------------------------------------------------------------------------------
metric                          value
sys.CurrentThreadCpuTime        17270000
Command [METRIC] finished with code: 0


Example of the metric registry output:
[source, text]
control.sh --metric io.dataregion.default
Command [METRIC] started
Arguments: --metric sys
--------------------------------------------------------------------------------
metric                          value
io.dataregion.default.TotalAllocatedSize          0
io.dataregion.default.LargeEntriesPagesCount      0
io.dataregion.default.PagesReplaced               0
io.dataregion.default.PhysicalMemorySize          0
io.dataregion.default.CheckpointBufferSize        0
io.dataregion.default.PagesReplaceRate            0
io.dataregion.default.InitialSize                 268435456
io.dataregion.default.PagesRead                   0
io.dataregion.default.AllocationRate              0
io.dataregion.default.OffHeapSize                 0
io.dataregion.default.UsedCheckpointBufferSize    0
io.dataregion.default.MaxSize                     6871947673
io.dataregion.default.OffheapUsedSize             0
io.dataregion.default.EmptyDataPages              0
io.dataregion.default.PagesFillFactor             0.0
io.dataregion.default.DirtyPages                  0
io.dataregion.default.TotalThrottlingTime         0
io.dataregion.default.EvictionRate                0
io.dataregion.default.PagesWritten                0
io.dataregion.default.TotalAllocatedPages         0
io.dataregion.default.PagesReplaceAge             0
io.dataregion.default.PhysicalMemoryPages         0
Command [METRIC] finished with code: 0

== Metric configure command

The metrics command configure bounds of histogram metrics or rate time interval of hitrate metric.

[tabs]
--
tab:Unix[]
[source,shell,subs="verbatim,quotes"]
----
control.sh --metric --configure-histogram histogram-metric-name 1,2,3
control.sh --metric --configure-hitrate hitrate-metric-name 1000
----
tab:Windows[]
[source,shell,subs="verbatim,quotes"]
----
control.bat --metric --configure-histogram histogram-metric-name 1,2,3
control.bat --metric --configure-hitrate hitrate-metric-name 1000
----
--

NOTE: For metric command use following format as metric name: `<register-name>.<metric-name>`: `io.datastorage.WalLoggingRate` must be set for `WalLoggingRate` metric.

== Indexes Management

The commands below allow to get a specific information on indexes and to trigger the indexes rebuild process.

To get the list of all indexes that match specified filters, use the command:

[tabs]
--
tab:Unix[]
[source,shell]
----
control.sh --cache indexes_list [--node-id nodeId] [--group-name grpRegExp] [--cache-name cacheRegExp] [--index-name idxNameRegExp]
----
tab:Window[]
[source,shell]
----
control.bat --cache indexes_list [--node-id nodeId] [--group-name grpRegExp] [--cache-name cacheRegExp] [--index-name idxNameRegExp]
----
--

Parameters:

[cols="1,3",opts="header"]
|===
| Parameter | Description
| `--node-id nodeId`| Node ID for the job execution. If the ID is not specified, a node is chosen by the grid.
| `--group-name regExp`| Regular expression enabling filtering by cache group name.
| `--cache-name regExp`| Regular expression enabling filtering by cache name.
| `--index-name regExp`| Regular expression enabling filtering by index name.
|===

To get the list of all caches that have index rebuild in progress, use the command below:


[tabs]
--
tab:Unix[]
[source,shell]
----
control.sh --cache indexes_rebuild_status [--node-id nodeId]
----
tab:Window[]
[source,shell]
----
control.bat --cache indexes_rebuild_status [--node-id nodeId]
----
--


To trigger the rebuild process of all indexes for the specified caches or the cache groups, use the command:

[tabs]
--
tab:Unix[]
[source,shell]
----
control.sh --cache indexes_force_rebuild --node-ids nodeId1,...nodeIdN|--all-nodes --cache-names cacheName1,...cacheNameN|--group-names groupName1,...groupNameN
----
tab:Window[]
[source,shell]
----
control.bat --cache indexes_force_rebuild --node-ids nodeId1,...nodeIdN|--all-nodes --cache-names cacheName1,...cacheNameN|--group-names groupName1,...groupNameN
----
--

Parameters:

[cols="1,3",opts="header"]
|===
| Parameter | Description
| `--node-id`| Node ID for the indexes rebuild.
| `--cache-names`| Comma-separated list of cache names for which indexes should be rebuilt.
| `--group-names`| Comma-separated list of cache group names for which indexes should be rebuilt.
|===


== System View Command

The system view command prints out the content of a system view provided in the parameters list. Use the `--node-id` parameter, if you need to get a metric from a specific node. Ignite selects a random node, if the `--node-id` is not set.

[tabs]
--
tab:Unix[]
[source,shell,subs="verbatim,quotes"]
----
control.sh --system-view views
----
tab:Windows[]
[source,shell,subs="verbatim,quotes"]
----
control.bat --system-view views
----
--


Examples of the output:

[source, text]
control.sh --system-view nodes
Command [SYSTEM-VIEW] started
Arguments: --system-view nodes
--------------------------------------------------------------------------------
nodeId                                  consistentId                                         version                          isClient    nodeOrder    addresses                                          hostnames          isLocal
a8a28869-cac6-4b17-946a-6f7f547b9f62    0:0:0:0:0:0:0:1%lo0,127.0.0.1,192.168.31.45:47500    2.10.0#20201230-sha1:00000000    false               1    [0:0:0:0:0:0:0:1%lo0, 127.0.0.1, 192.168.31.45]    [192.168.31.45]    true
d580433d-c621-45ff-a558-b4df82d09613    0:0:0:0:0:0:0:1%lo0,127.0.0.1,192.168.31.45:47501    2.10.0#20201230-sha1:00000000    false               2    [0:0:0:0:0:0:0:1%lo0, 127.0.0.1, 192.168.31.45]    [192.168.31.45]    false
Command [SYSTEM-VIEW] finished with code: 0


[source, text]
control.sh --system-view views
Command [SYSTEM-VIEW] started
Arguments: --system-view views
--------------------------------------------------------------------------------
name                           schema    description
NODES                          SYS       Cluster nodes
SQL_QUERIES_HISTORY            SYS       SQL queries history.
INDEXES                        SYS       SQL indexes
BASELINE_NODES                 SYS       Baseline topology nodes
STRIPED_THREADPOOL_QUEUE       SYS       Striped thread pool task queue
LOCAL_CACHE_GROUPS_IO          SYS       Local node IO statistics for cache groups
SCAN_QUERIES                   SYS       Scan queries
CLIENT_CONNECTIONS             SYS       Client connections
PARTITION_STATES               SYS       Distribution of cache group partitions across cluster nodes
VIEW_COLUMNS                   SYS       SQL view columns
SQL_QUERIES                    SYS       Running SQL queries.
CACHE_GROUP_PAGE_LISTS         SYS       Cache group page lists
METRICS                        SYS       Ignite metrics
CONTINUOUS_QUERIES             SYS       Continuous queries
TABLE_COLUMNS                  SYS       SQL table columns
TABLES                         SYS       SQL tables
DISTRIBUTED_METASTORAGE        SYS       Distributed metastorage data
SERVICES                       SYS       Services
DATASTREAM_THREADPOOL_QUEUE    SYS       Datastream thread pool task queue
NODE_METRICS                   SYS       Node metrics
BINARY_METADATA                SYS       Binary metadata
JOBS                           SYS       Running compute jobs, part of compute task started on remote host.
SCHEMAS                        SYS       SQL schemas
CACHE_GROUPS                   SYS       Cache groups
VIEWS                          SYS       SQL views
DATA_REGION_PAGE_LISTS         SYS       Data region page lists
NODE_ATTRIBUTES                SYS       Node attributes
TRANSACTIONS                   SYS       Running transactions
CACHES                         SYS       Caches
TASKS                          SYS       Running compute tasks
Command [SYSTEM-VIEW] finished with code: 0


== Working With Persistence Data

[WARNING]
====
All `--persistence` commands below function exclusively in link:maintenance-mode[Maintenance Mode]
====

=== Displaying Information About Damaged Caches

Use the `--persistence info` option to display information about potentially damaged caches in the local node:

[tabs]
--
tab:Unix[]
[source,shell]
----
control.sh --persistence info
----
tab:Window[]
[source,shell]
----
control.bat --persistence info
----
--

=== Cleaning Up Damaged Caches

Use the `--persistence clean corrupted` option to clear directories containing caches with corrupted data files:

[tabs]
--
tab:Unix[]
[source,shell]
----
control.sh --persistence clean corrupted
----
tab:Window[]
[source,shell]
----
control.bat --persistence clean corrupted
----
--

=== Clearing All Caches

Use the `--persistence clean all` option to delete all cache directories:

[tabs]
--
tab:Unix[]
[source,shell]
----
control.sh --persistence clean all
----
tab:Window[]
[source,shell]
----
control.bat --persistence clean all
----
--

=== Clearing Specific Caches

Use the `--persistence clean caches` option to delete specific listed caches:

[tabs]
--
tab:Unix[]
[source,shell]
----
control.sh --persistence clean caches cache1,cache2,cache3
----
tab:Window[]
[source,shell]
----
control.bat --persistence clean caches cache1,cache2,cache3
----
--

where `cache1,cache2,cache3` are comma-separated cache names.

=== Backing Up Damaged Files

Use the `--persistence backup corrupted` option to back up corrupted data files:

[tabs]
--
tab:Unix[]
[source,shell]
----
control.sh --persistence backup corrupted
----
tab:Window[]
[source,shell]
----
control.bat --persistence backup corrupted
----
--

=== Backing Up All Cache Files

Use the `--persistence backup all` option to back up all cache data files:

[tabs]
--
tab:Unix[]
[source,shell]
----
control.sh --persistence backup all
----
tab:Window[]
[source,shell]
----
control.bat --persistence backup all
----
--

=== Backing Up Specific Cache Files

Use the `--persistence backup caches` option to back up specified cache data files:

[tabs]
--
tab:Unix[]
[source,shell]
----
control.sh --persistence backup caches cache1,cache2,cache3
----
tab:Window[]
[source,shell]
----
control.bat --persistence backup caches cache1,cache2,cache3
----
--

where `cache1,cache2,cache3` are comma-separated cache names.

The layout these backup files are stored is `{IGNITE_WORK_DIR}/db/{nodeId}/backup_cache-{CACHE_NAME}`.

[WARNING]
====
Backup files created via the `./control.sh --persistence backup ...` commands should not be regarded as snapshot recovery mechanisms.
These are exact copies of folders containing caches intended for subsequent analysis of the causes of corruption or attempts to recover data, but it's important to remember that these operations require specialized knowledge, and there are no universal methods for analyzing and recovering corrupted caches.
====

After completing all manipulations with the copied corrupted data backed up or if they become unnecessary, they can be manually deleted from the above-specified directory.

== Defragmentation

=== Scheduling Defragmentation

Use the `--defragmentation schedule` option to schedule Persistent Data Store (PDS) defragmentation:

[tabs]
--
tab:Unix[]
[source,shell]
----
control.sh --defragmentation schedule --nodes consistentId0,consistentId1 [--caches cache1,cache2,cache3]
----
tab:Window[]
[source,shell]
----
control.bat --defragmentation schedule --nodes consistentId0,consistentId1 [--caches cache1,cache2,cache3]
----
--

As a result, the next node start-up will occur in Maintenance Mode, during which the defragmentation will be performed automatically.
To exit Maintenance Mode afterward, simply restart the node.

=== Checking Defragmentation Status

[WARNING]
====
Available Exclusively in link:maintenance-mode[Maintenance Mode]
====

Use the `--defragmentation status` option to retrieve the status of ongoing defragmentation processes:

[tabs]
--
tab:Unix[]
[source,shell]
----
control.sh --defragmentation status
----
tab:Window[]
[source,shell]
----
control.bat --defragmentation status
----
--

=== Canceling Defragmentation

[WARNING]
====
Available Exclusively in link:maintenance-mode[Maintenance Mode]
====

Use the `--defragmentation cancel` option to cancel either a scheduled or active Persistent Data Store (PDS) defragmentation:

[tabs]
--
tab:Unix[]
[source,shell]
----
control.sh --defragmentation cancel
----
tab:Window[]
[source,shell]
----
control.bat --defragmentation cancel
----
--


== Performance Statistics

Ignite provides a built-in tool for cluster profiling. Read link:monitoring-metrics/performance-statistics[Performance Statistics] for more information.


[tabs]
--
tab:Unix[]
[source,shell]
----
control.sh --performance-statistics [start|stop|rotate|status]
----
tab:Window[]
[source,shell]
----
control.bat --performance-statistics [start|stop|rotate|status]
----
--

Parameters:

[cols="1,3",opts="header"]
|===
| Parameter | Description
| `start`| Start collecting performance statistics in the cluster.
| `stop`| Stop collecting performance statistics in the cluster.
| `rotate`| Rotate collecting performance statistics in the cluster.
| `status`| Get status of collecting performance statistics in the cluster.
|===

== Working with Cluster Properties

The `control.sh|bat` script allows administrators to view and modify cluster-wide properties.

To get the full list of available properties, use the `--property list` command. This command returns the list of all available properties to work with:

[tabs]
--
tab:Unix[]
[source,shell]
----
control.sh --property list
----
tab:Windows[]
[source,shell]
----
control.bat --property list
----
--

You can set property value with `--property set` command. For example, to enable or disable SQL statistics in cluster use, specify `ON`, `OFF`,  or `NO_UPDATE` values:

[tabs]
--
tab:Unix[]
[source,shell]
----
control.sh --property set --name 'statistics.usage.state' --val 'ON'
----
tab:Windows[]
[source,shell]
----
control.bat --property set --name 'statistics.usage.state' --val 'ON'
----
--

You can also get property value with `--property get` command:

[tabs]
--
tab:Unix[]
[source,shell]
----
control.sh --property get --name 'statistics.usage.state'
----
tab:Windows[]
[source,shell]
----
control.bat --property get --name 'statistics.usage.state'
----
--

NOTE: Available values depend on the property.
For example, link:SQL/sql-statistics[SQL statistics,window=_blank] use `ON|OFF|NO_UPDATE`, while link:#managing_cluster_connection_properties[Cluster Connection Properties,window=_blank]
use `true|false`.

=== Managing Cluster Connection Properties

You can control whether new client or server connections are accepted by the cluster setting the cluster-wide properties.

The following properties are available:

[cols="3,5,2,2", opts="header"]
|===
|Property | Description | Available values | Default value
|newClientNodeConnectionsEnabled | If true then new client node connections allowed. | true / false | true
|newServerNodeConnectionsEnabled | If true then new server node connections allowed. | true / false | true
|newThinConnectionsEnabled | If true then new thin client connections allowed. | true / false | true
|newJdbcConnectionsEnabled | If true then new JDBC connections allowed. | true / false | true
|newOdbcConnectionsEnabled | If true then new ODBC connections allowed. | true / false | true
|===

NOTE: Setting a property to `false` affects only new connections. Existing connections remain active.

For example, the following command disables new thin client connections:

[tabs]
--
tab:Unix[]
[source,shell]
----
control.sh --property set --name newThinConnectionsEnabled --val false
----
tab:Windows[]
[source,shell]
----
control.bat --property set --name newThinConnectionsEnabled --val false
----
--

== Manage cache metrics collection

The command provides an ability to enable, disable or show status of cache metrics collection.

[source, shell]
----
control.sh|bat --cache metrics enable|disable|status --caches cache1[,...,cacheN]|--all-caches
----

Parameters:

[cols="1,3",opts="header"]
|===
| Parameter | Description
| `--caches cache1[,...,cacheN]`| Specifies a comma-separated list of cache names to which operation should be applied.
| `--all-caches` | Applies operation to all user caches.
|===

Examples:
[source, shell]
----
# Show metrics statuses for all caches:
control.sh|bat --cache metrics status --all-caches

# Enable metrics collection for cache-1 and cache-2:
control.sh|bat --cache metrics enable --caches cache-2,cache-1
----

== Rebuild index

The `schedule_indexes_rebuild` command instructs Apache Ignite to schedule the rebuild of indexes for the specified caches or cache groups. This will result in the specified nodes being scheduled to start in link:maintenance-mode[Maintenance Mode] during the next startup.

[source, shell]
----
 control.sh|bat --cache schedule_indexes_rebuild --node-ids nodeId1,...nodeIdN|--all-nodes --cache-names cacheName[index1,...indexN],cacheName2,cacheName3[index1] --group-names groupName1,groupName2,...groupNameN
----

Parameters:

[cols="1,3",opts="header"]
|===
| Parameter | Description
|--node-id | A list of nodes to rebuild indexes on. If not specified, schedules rebuild on all nodes.
|--cache-names | Comma-separated list of cache names, optionally with indexes. If indexes are not specified, all indexes of the cache will be scheduled for the rebuild operation. Can be used simultaneously with cache group names.
|--group-names | Comma-separated list of cache group names. Can be used simultaneously with cache names.
|===


== Event management

The control utility provides commands to enable, disable and check the status of events on all server nodes.

=== Enable/disable events

To enable or disable events on all server nodes, use the `--event enable/disable` command.

[source, shell]
----
control.sh|bat --event enable|disable event1[,...,eventN]
----

Parameters:

[cols="1,3",opts="header"]
|===
| Parameter | Description
| `event1[,...,eventN]`| Specifies a comma-separated list of events to enable/disable.
|===

Examples:
[source, shell]
----
control.sh|bat --event enable EVT_CACHE_STARTED,EVT_CACHE_STOPPED
control.sh|bat --event disable EVT_CACHE_STARTED,EVT_CACHE_STOPPED
----

=== Events list and status

To get the list and status of available events, use the `--event list` command.

[source, shell]
----
control.sh|bat --event list [--enabled]
----

Parameters:

[cols="1,3",opts="header"]
|===
| Parameter | Description
| `--enabled`| List only enabled evente.
|===

Examples:
[source, shell]
----
control.sh|bat --event list --enabled
----

== TLS Certificates

A node reads its TLS certificates once, when it starts. Updating them normally means restarting it. The
`--ssl reload` command does it on a running cluster instead: every node, server and client, re-reads its key and
trust stores. It covers the communication, discovery, client connector and REST transports, binary and HTTP alike.

Everything that takes part in a rotation needs the files placed at the paths it is configured with. What differs is
what you run afterwards:

* *server nodes* — run the reload command once, and it reaches every node in the topology;
* *client nodes*, meaning an application started as an Ignite node — nothing to run, the same command reaches them
too;
* *JDBC and ODBC applications* — nothing to run and nothing to restart: every new connection reads the stores from
disk again;
* *thin-client applications* — nothing to run either, but one that is already running keeps the stores it read at
start. It reads them again only after a handshake was refused: that attempt fails, and the next one uses the files
that are on disk now.

The command reaches what is in the topology when it runs, and nothing else. Applications are never reached, which
is why the steps below say when each of their files has to be in place; a node that was down during a step comes
back with the files it had when it stopped, so give it the current ones before it rejoins.

Place a file by writing it next to the one in use and renaming it over, so that nothing can read a half-written
store.

A reload never revokes anything. A peer you removed from a trust store keeps its open connections until they close
on their own. A node logs a refused handshake with the reason reported by the TLS engine, so a rotation done out of
order is visible rather than silent.

Everything reloads except two arrangements, which the report names as not reloaded rather than as a success:

* a factory of your own whose `create()` hands back a cached context;
* a Jetty configuration for HTTP REST that sets a ready-made `sslContext` instead of a key store path.

Neither has a file to read again. They take no part in a rotation and keep the certificate they started with until
the node restarts, so a rotation that ends with the old authority removed locks them out.

=== Reloading Certificates

Put the new key store or trust store at the path a node is already configured with, and run the command. Nothing in
the configuration changes: the node re-reads what it points at.

[source, shell]
----
control.sh|bat --ssl reload
----

The command works in two phases. First every node builds the certificates that are on disk and checks them,
without putting any of them in use, and reports what it found:

[source,text]
----
e1e18f84-0fb5-484d-a623-15ffe3800000: can be reloaded client connector, communication, discovery; serving CN=node01 until 2039-11-07
0cf9e4e2-bb7a-466a-a113-b6230b500001: can be reloaded client connector, communication, discovery; serving CN=node01 until 2039-11-07
----

One line per SSL context factory: transports configured with the same one share the context, so they are reloaded
together and reported together. A node configured with several factories answers with several lines.

Everything that can fail happens in this phase. A node that would not be able to use the new certificate says so,
and the command stops without having changed anything on any node:

[source,text]
----
46db5416-d199-48d6-a807-88b7f1300000: would fail on client connector, communication, discovery (No trusted certificate found)
----

A certificate the node's own trust store rejects counts as unusable, and is checked whenever any of the transports
sharing that factory connects nodes to each other. This assumes every node runs the same key and trust store
configuration. The same answer comes back when the trust stores hold the node certificates themselves rather than
the certificate of an authority, which is the scheme the link:security/ssl-tls[SSL/TLS] page describes; replacing
a certificate is then a change of trust, so give the new one to every trust store first, the way the next section
gives them a new authority.

When every node is ready, the command asks before it goes on. The second phase then puts in use exactly what the
first one checked — a node applies only what the same run prepared, never what some other run left behind — and
reports it:

[source,text]
----
e1e18f84-0fb5-484d-a623-15ffe3800000: reloaded client connector, communication, discovery; serving CN=node01 until 2041-02-14
0cf9e4e2-bb7a-466a-a113-b6230b500001: reloaded client connector, communication, discovery; serving CN=node01 until 2041-02-14
----

The name stays the same, because the new certificate was issued for the same node; the expiry date is what moved.
A node that joined while the question was on screen has nothing prepared, is reported as not reloaded, and keeps
the certificates it read when it started.

The HTTP REST connector is the one part that rebuilds in place instead of holding the new certificates aside, so
it is also the only one that can still fail in this phase. It carries no traffic between nodes, so a failure there
cannot split the cluster.

New connections use the new certificate. Existing ones keep the certificate they were opened with, and nothing
interrupts them, so for a while a node serves both.

`--dry-run` stops after the first phase and throws away what it built, so it changes nothing and asks nothing:

[source, shell]
----
control.sh|bat --ssl reload --dry-run
----

=== Replacing the Certificate Authority

Nodes and clients authenticate each other, so the order is not a matter of taste: everything has to trust the new
authority before anything starts presenting a certificate issued by it, and the old authority has to stay until
nothing presents it any more.

. *Trust the new authority.* Everything then trusts both, and still presents the old certificate.
+
--
*On every node*, server and client alike:

* work on a copy, so that nothing ever reads a half-written store:
+
.Example
[source, shell]
----
cp trust.jks trust.jks.new
----
* add the certificate of the new authority, keeping the old one. Without `-noprompt` keytool asks whether to trust
it, and a run that cannot answer leaves the store unchanged and still exits with zero:
+
.Example
[source, shell]
----
keytool -importcert -keystore trust.jks.new -alias newca -file newca.crt -noprompt
----
* put it in place:
+
.Example
[source, shell]
----
mv trust.jks.new trust.jks
----

*Applications.* The same edit to their own trust store, with the path each one is configured with. Any moment
before step 2 will do. From that step on the cluster presents a certificate issued by the new authority, and an
application that does not trust it yet cannot open a connection.

*Once for the whole cluster.* Put it in use on the nodes:

[source, shell]
----
control.sh|bat --ssl reload
----
--

. *Present the new certificate.* Everything then presents it, and is still trusted because the old authority is
also still there.
+
--
*On every node:*

* work on a copy of the key store this node already runs on — its key stays, only the certificate changes:
+
.Example
[source, shell]
----
cp node.jks node.jks.new
----
* install the certificate the new authority issued for that key. A reply that carries the whole chain goes in as
it is; one that carries the node certificate alone needs the authority's own certificate imported before it, or
there is nothing to chain the reply to:
+
.Example
[source, shell]
----
keytool -importcert -keystore node.jks.new -alias node -file node.crt -noprompt
----
* put it in place:
+
.Example
[source, shell]
----
mv node.jks.new node.jks
----

The store and the private key inside it have to open with the one password the node is configured with, because it
opens both with that one. Keep one key entry per store as well: if it holds several, the JSSE key manager picks one
of them and you cannot influence which.

*Applications that present a certificate of their own.* Place the new key store at any moment after step 1 and
before step 3. Earlier, the cluster does not trust the new authority yet; later, step 3 has already checked what
the application was given.

*Once for the whole cluster.* This is the step that catches a node whose new key store its own trust store does
not accept, which is what a skipped step 1 looks like on that node. The command reports it before it puts anything
in use anywhere, so read the report and answer the question it asks:

[source, shell]
----
control.sh|bat --ssl reload
----
--

. *Check that nothing presents the old certificate any more.* Step 4 takes the old authority away, and anything
that still presents a certificate from it is locked out. This is the gate for that step, not a formality.
+
--
*Nodes.* Step 2 has already answered this for every node that was in the topology: its report names what each of
them serves now.

*Everything the command does not reach* — applications that present a certificate of their own, and whatever nodes
and applications are provisioned from, such as images and configuration management. Nothing reports on those, so
read back the issuer of the certificate each of them holds, and expect the new authority in every answer:

.Example
[source, shell]
----
keytool -list -v -keystore node.jks -alias node | grep Issuer
----

What matters here is the key stores, not the connections.
--

. *Stop trusting the old authority.* Nothing presents a certificate signed by it, so nothing loses trust.
+
--
*On every node:*

* work on a copy again:
+
.Example
[source, shell]
----
cp trust.jks trust.jks.new
----
* remove the entry of the old authority, and leave the rest alone. Its alias is whatever it was given when the
store was made, so list the store first:
+
.Example
[source, shell]
----
keytool -list -keystore trust.jks.new
keytool -delete -keystore trust.jks.new -alias oldca
----
* put it in place:
+
.Example
[source, shell]
----
mv trust.jks.new trust.jks
----

*Applications.* The same edit to their own trust store, in any order with the nodes — by now nothing presents a
certificate from the old authority. A JDBC or ODBC application uses the narrowed store on its next connection; a
thin client that is already running keeps the wider one until it is restarted, because nothing refuses its
handshake any more.

*Once for the whole cluster.* Put it in use on the nodes:

[source, shell]
----
control.sh|bat --ssl reload
----
--

Doing the last step before the one before it throws nodes out of the cluster: they would stop trusting a
certificate that some peer still presents.
